using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using System.IO;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Media;

namespace DesktopFarm {
public class Hit { public Rectangle Bounds;public Action Action;public string Hint; }
public partial class GameForm:Form {
 public Farm F;public string SavePath;public bool Testing;readonly Timer timer=new Timer();NotifyIcon tray;readonly List<Hit> hits=new List<Hit>();
 WallpaperForm wallpaper,wallpaperPreview;LiveFarmHost engineHost;double nextWallpaperAttempt;bool awaitingDesktop;DateTime desktopRequested;
 readonly Dictionary<string,Font> fonts=new Dictionary<string,Font>();
 string panel="",tab="",selected="wheat",placement=null,toast="欢迎回家，农场在等你。",tip="";int page=0,hoverPlot=-1,decorMove=-1;
 double toastUntil=0,lastSave=0,animation=0,trainUntil=0;bool runtimePrompted=false,exitRequested=false,watering=false,desktop=false,saveFailed=false,disposed=false,hotkeyRegistered=false;
 Point mouseWorld,mouseLogical;DateTime lastFrame=DateTime.Now;Rectangle normalBounds;Icon ownIcon;SoundPlayer musicPlayer;readonly Dictionary<string,SoundPlayer> sounds=new Dictionary<string,SoundPlayer>();
 public static readonly Color Ink=PixelArt.C("3f4c43"),Muted=PixelArt.C("7b8572"),Paper=PixelArt.C("f7f1dc"),Green=PixelArt.C("59785c"),Line=PixelArt.C("d8d4b8"),Gold=PixelArt.C("ae8550");
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetClassName(IntPtr h,StringBuilder b,int n);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);
 [DllImport("user32.dll")]static extern bool SetWindowPos(IntPtr h,IntPtr after,int x,int y,int cx,int cy,uint flags);
 [DllImport("user32.dll")]static extern bool RegisterHotKey(IntPtr h,int id,uint mods,uint key);
 [DllImport("user32.dll")]static extern bool UnregisterHotKey(IntPtr h,int id);
 [DllImport("user32.dll")]static extern bool DestroyIcon(IntPtr h);
 protected override bool ShowWithoutActivation {get{return desktop;}}
 public GameForm(Farm farm,string savePath,bool testing){F=farm;SavePath=savePath;Testing=testing;L.SetLanguage(F.S.Language);selected=Farm.Crop(F.S.SelectedSeed)!=null&&F.Level>=Farm.Crop(F.S.SelectedSeed).Level?F.S.SelectedSeed:"wheat";Text=L.T("Mosslight · 苔光桌面农场");AccessibleName=Text;FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;DoubleBuffered=true;SetStyle(ControlStyles.AllPaintingInWmPaint|ControlStyles.UserPaint|ControlStyles.OptimizedDoubleBuffer,true);KeyPreview=true;BackColor=Paper;
 var area=Screen.PrimaryScreen.WorkingArea;float fit=Math.Min(1f,Math.Min((area.Width-80)/1200f,(area.Height-100)/800f));ClientSize=new Size((int)(1200*fit),(int)(800*fit));MinimumSize=Size;normalBounds=Bounds;
 using(var bmp=new Bitmap(32,32)){using(var g=Graphics.FromImage(bmp)){g.Clear(PixelArt.C("547457"));PixelArt.Crop(g,5,8,"wheat",1,false,false,0);}IntPtr iconHandle=bmp.GetHicon();using(var temp=Icon.FromHandle(iconHandle))ownIcon=(Icon)temp.Clone();DestroyIcon(iconHandle);}Icon=ownIcon;
 tray=new NotifyIcon{Icon=ownIcon,Visible=true};UpdateLabels();tray.DoubleClick+=(sender,e)=>ExpandWindow();
 timer.Interval=80;timer.Tick+=(s,e)=>Frame();timer.Start();FormClosing+=HandleClosing;Shown+=(s,e)=>{normalBounds=Bounds;if(Program.ManageLaunch)ExpandWindow();else if(Program.StartupLaunch||Program.DesktopLaunch)SetDesktop(true);else if(!F.S.IntroSeen)panel="welcome";else if(F.S.Desktop||F.S.WallpaperEnabled)SetDesktop(true);if(F.LoadNotice!="")Toast(F.LoadNotice);else if(F.Notices.Count>0){Toast(F.Notices.Last());F.Notices.Clear();}};
 if(F.S.Music)SetMusic(true);
 }
 public static bool ShouldStayInTray(CloseReason reason,bool wallpaperEnabled,bool explicitExit,bool testing){return reason==CloseReason.UserClosing&&wallpaperEnabled&&!explicitExit&&!testing;}
 void HandleClosing(object sender,FormClosingEventArgs e){if(ShouldStayInTray(e.CloseReason,F.S.WallpaperEnabled,exitRequested,Testing)){e.Cancel=true;desktop=true;F.S.Desktop=true;Hide();SaveGame();RuntimeLog.Write("Management window hidden; wallpaper remains active");}else{SaveGame();if(!Testing)RuntimeLog.Write("Exiting: "+e.CloseReason+"; explicit="+exitRequested);}}
 public void ExitGame(){exitRequested=true;Close();}
 public string CurrentPanel {get{return panel;}}public bool DesktopMode {get{return desktop;}}
 void Frame(){if(disposed)return;EnsureShortcut();if(Program.QuitSignal!=null&&Program.QuitSignal.WaitOne(0)){ExitGame();return;}if(Program.DesktopSignal!=null&&Program.DesktopSignal.WaitOne(0))SetDesktop(true);if(Program.OpenSignal!=null&&Program.OpenSignal.WaitOne(0))ExpandWindow();if(awaitingDesktop){if(engineHost!=null&&engineHost.DesktopReady){awaitingDesktop=false;Hide();}else if((DateTime.UtcNow-desktopRequested).TotalSeconds>30){awaitingDesktop=false;desktop=false;Show();Toast("桌面连接尚未完成，请点击设为桌面背景重试。");}}double now=F.Now;animation+=(DateTime.Now-lastFrame).TotalSeconds;lastFrame=DateTime.Now;F.Tick();if(F.Notices.Count>0){Toast(F.Notices.Last());F.Notices.Clear();}if(now-lastSave>15){SaveGame();lastSave=now;}timer.Interval=!Visible?250:F.S.Quiet?240:80;if(Visible)Invalidate();if(engineHost!=null)engineHost.Pulse();else if(!Testing&&F.S.WallpaperEnabled&&now>nextWallpaperAttempt){nextWallpaperAttempt=now+5;if(EnsureWallpaper()&&F.S.Desktop){desktop=true;Hide();}}}
 public void SaveGame(){if(Testing)return;try{F.Save(SavePath);saveFailed=false;}catch(Exception e){if(!saveFailed){toast="存档暂时写入失败："+e.Message;toastUntil=F.Now+15;}saveFailed=true;}}
 void Toast(string message){toast=message;toastUntil=F.Now+6;}
 void Act(Func<string> f,string sound="click"){Toast(f());SaveGame();Play(sound);Invalidate();}
 void Open(string name){if(desktop){SetDesktop(false);}panel=name;page=0;tab="";placement=null;decorMove=-1;Invalidate();}
 protected override void OnHandleCreated(EventArgs e){base.OnHandleCreated(e);EnsureShortcut();} protected override void OnHandleDestroyed(EventArgs e){UnregisterHotKey(Handle,shortcutId);hotkeyRegistered=false;base.OnHandleDestroyed(e);} protected override void WndProc(ref Message m){if(m.Msg==0x0312&&m.WParam.ToInt32()==shortcutId){if(desktop||!Visible)ExpandWindow();else SetDesktop(true);return;}base.WndProc(ref m);}
 void UpdateLabels(){Text=L.T("Mosslight · 苔光桌面农场");AccessibleName=Text;tray.Text=L.T("苔光农场 · 安心忙碌，慢慢生长");var old=tray.ContextMenuStrip;var menu=new ContextMenuStrip();menu.Items.Add(L.T("打开农场"),null,(sender,e)=>ExpandWindow());menu.Items.Add(L.T("设为桌面背景"),null,(sender,e)=>SetDesktop(true));menu.Items.Add(L.T("布置桌面"),null,(sender,e)=>ShowWallpaperPreview());menu.Items.Add(L.T("恢复原桌面"),null,(sender,e)=>StopWallpaper());menu.Items.Add(L.T("修复桌面"),null,(sender,e)=>{if(engineHost!=null)engineHost.RequestRepair(true);else SetDesktop(true);});menu.Items.Add("中文 / English",null,(sender,e)=>ToggleLanguage());menu.Items.Add(L.T("保存并退出"),null,(sender,e)=>ExitGame());tray.ContextMenuStrip=menu;if(old!=null)old.Dispose();}
 void ToggleLanguage(){F.S.Language=F.S.Language=="en"?"zh-CN":"en";L.SetLanguage(F.S.Language);F.S.Language=L.Code;UpdateLabels();SaveGame();Toast("语言已切换，存档进度保持不变。");Invalidate();if(wallpaper!=null)wallpaper.Invalidate();if(wallpaperPreview!=null)wallpaperPreview.Invalidate();}
 bool EnsureWallpaper(){if(!Testing&&!NativeDesktop.RuntimeAvailable){F.S.WallpaperEnabled=false;F.S.Desktop=false;SaveGame();if(!runtimePrompted){runtimePrompted=true;MessageBox.Show(L.T("需要免费的 Microsoft WebView2 显示组件。请运行游戏文件夹内 runtime/MicrosoftEdgeWebview2Setup.exe，安装完成后再次点击设为桌面背景。"),"Mosslight");}return false;}if(engineHost!=null&&engineHost.Active)return true;if(!Testing){try{engineHost=new LiveFarmHost(this,F,()=>{UpdateLabels();SaveGame();},name=>{ExpandWindow();if(name!="")Open(name);},SavePath);engineHost.Start();return true;}catch(Exception e){if(engineHost!=null){engineHost.Dispose();engineHost=null;}Toast("动态壁纸连接失败："+e.Message);return false;}}Toast("请先运行 Wallpaper Engine，再启用动态农场壁纸。");return false;}
 public void SetDesktop(bool enabled){panel="";placement=null;decorMove=-1;if(enabled){if(!EnsureWallpaper()){desktop=false;Show();Activate();return;}F.S.WallpaperEnabled=true;F.S.Desktop=true;desktop=true;SaveGame();desktopRequested=DateTime.UtcNow;awaitingDesktop=true;engineHost.RequestRepair(true);Toast("正在连接互动桌面，请稍候。");}else{desktop=false;F.S.Desktop=false;Show();WindowState=FormWindowState.Normal;Activate();SaveGame();}Invalidate();}
 void StopWallpaper(){if(engineHost!=null){engineHost.Dispose();engineHost=null;}if(wallpaper!=null){wallpaper.Close();wallpaper=null;}F.S.WallpaperEnabled=false;F.S.Desktop=false;desktop=false;ExpandWindow();Act(()=>"已恢复原来的桌面背景。");}
 void ShowWallpaperPreview(){if(engineHost!=null&&engineHost.Active){engineHost.ShowPanel("decor");SetDesktop(true);return;}if(wallpaperPreview!=null&&!wallpaperPreview.IsDisposed){wallpaperPreview.Activate();return;}wallpaperPreview=new WallpaperForm(F,name=>{ExpandWindow();if(name!="")Open(name);},SaveGame,true);wallpaperPreview.Show();wallpaperPreview.Activate();}
 void ExpandWindow(){awaitingDesktop=false;desktop=false;F.S.Desktop=false;Show();WindowState=FormWindowState.Normal;Activate();}
 public string WallpaperStatus {get{return engineHost==null?"not attached":engineHost.Status;}}
 Font FontOf(int size,bool bold=false){string key=size+"/"+bold;if(!fonts.ContainsKey(key))fonts[key]=new Font("Microsoft YaHei UI",size,bold?FontStyle.Bold:FontStyle.Regular,GraphicsUnit.Pixel);return fonts[key];}
 void Fill(Graphics g,Color c,int x,int y,int w,int h){using(var b=new SolidBrush(c))g.FillRectangle(b,x,y,w,h);}
 void Border(Graphics g,Color c,int x,int y,int w,int h,int weight=1){using(var p=new Pen(c,weight))g.DrawRectangle(p,x,y,w,h);}
 void TextAt(Graphics g,string text,int x,int y,int size=16,Color? color=null,bool bold=false,int width=1100,int height=50){text=L.T(text);if(L.IsEnglish&&width<400&&height==50&&!text.Contains("\n")){while(size>10&&g.MeasureString(text,FontOf(size,bold)).Width>width-2)size--;}using(var b=new SolidBrush(color??Ink))using(var sf=new StringFormat()){sf.Trimming=StringTrimming.EllipsisCharacter;g.DrawString(text,FontOf(size,bold),b,new RectangleF(x,y,width,height),sf);}}
 void Center(Graphics g,string text,Rectangle r,int size,Color color,bool bold=false){text=L.T(text);while(size>10&&g.MeasureString(text,FontOf(size,bold)).Width>r.Width-8)size--;using(var b=new SolidBrush(color))using(var sf=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center,Trimming=StringTrimming.EllipsisCharacter})g.DrawString(text,FontOf(size,bold),b,r,sf);}
 void Card(Graphics g,int x,int y,int w,int h,Color? color=null){Fill(g,Color.FromArgb(32,46,53,36),x+3,y+5,w,h);Fill(g,color??Paper,x,y,w,h);Border(g,Line,x,y,w,h);Fill(g,PixelArt.C("fff9e5"),x+1,y+1,w-2,2);}
 void Button(Graphics g,string label,int x,int y,int w,int h,Action action,bool primary=false,bool enabled=true,string hint=""){var r=new Rectangle(x,y,w,h);bool over=r.Contains(mouseLogical);Color bg=!enabled?PixelArt.C("e1e1cd"):primary?(over?PixelArt.C("6f8c65"):Green):(over?PixelArt.C("eee5ca"):PixelArt.C("f5efda"));Fill(g,PixelArt.C("b8bba1"),x,y+3,w,h);Fill(g,bg,x,y,w,h);Border(g,primary?Green:Line,x,y,w,h);Center(g,label,r,15,!enabled?Muted:primary?PixelArt.C("fff7dd"):Ink,true);hits.Add(new Hit{Bounds=r,Action=action,Hint=hint});}
 void HitArea(int x,int y,int w,int h,Action a,string hint=""){hits.Add(new Hit{Bounds=new Rectangle(x,y,w,h),Action=a,Hint=hint});}
 void Badge(Graphics g,string label,int x,int y,int w,Color color){Fill(g,color,x,y,w,24);Center(g,label,new Rectangle(x,y,w,24),12,Paper,true);}
 public Bitmap RenderPanelSnapshot(string name,string inner){string before=panel,oldTab=tab;panel=name;tab=inner;try{return RenderSnapshot();}finally{panel=before;tab=oldTab;}} public Bitmap RenderSnapshot(){var b=new Bitmap(1200,800);using(var g=Graphics.FromImage(b)){g.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;hits.Clear();DrawFull(g);}return b;}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var frame=RenderSnapshot()){e.Graphics.InterpolationMode=InterpolationMode.NearestNeighbor;e.Graphics.PixelOffsetMode=PixelOffsetMode.Half;e.Graphics.DrawImage(frame,new Rectangle(0,0,ClientSize.Width,ClientSize.Height));}}
 void DrawFull(Graphics g){g.Clear(Paper);using(var world=PixelArt.World(F,animation,false,hoverPlot,placement,mouseWorld)){g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(world,new Rectangle(0,78,1200,600));}
 Fill(g,PixelArt.C("f7f2df"),0,0,1200,78);Fill(g,Line,0,77,1200,1);TextAt(g,"苔光农场",29,15,27,Ink,true,220);TextAt(g,"M O S S L I G H T   /   D E S K T O P  F A R M",30,51,10,Muted,false,360);
 TextAt(g,"Lv. "+F.Level,348,17,19,Green,true,100);int next=Farm.Threshold(Math.Min(20,F.Level+1)),prev=Farm.Threshold(F.Level);Fill(g,PixelArt.C("dcdcc4"),350,49,157,6);Fill(g,PixelArt.C("91a576"),350,49,F.Level==20?157:(int)(157*Math.Min(1,(F.S.Xp-prev)/(double)(next-prev))),6);TextAt(g,F.Level==20?"山谷守护者":(F.S.Xp-prev)+" / "+(next-prev)+" XP",422,21,11,Muted,false,100);
 Fill(g,PixelArt.C("eee7c9"),550,18,146,42);TextAt(g,"G",562,24,21,Gold,true,28);TextAt(g,Farm.MaintenanceBuild?"∞":F.S.Coins.ToString("N0"),596,25,19,Ink,true,90);
 bool night=F.IsNight;TextAt(g,(night?"月色温柔":"晴光正好")+"  ·  "+DateTime.Now.ToString("HH:mm"),728,28,15,Muted,false,190);
#if MAINTENANCE_BUILD
 TextAt(g,"检修版 · 无限金币 · 建造 1 分钟",718,53,11,Gold,true,220);
#endif
 Button(g,"桌面陪伴",945,20,111,35,()=>SetDesktop(true),true,true,ShortcutKeys.Label(F.S.HotkeyMods,F.S.HotkeyKey));Button(g,"设置",1070,20,99,35,()=>Open("settings"));
 HitArea(0,79,1200,583,()=>WorldClick(mouseWorld));
 if(panel==""){
 Card(g,24,106,247,132,PixelArt.C("f4efda"));TextAt(g,"山谷手札  /  "+(Math.Min(F.S.Guide,6)+1).ToString("00"),40,120,12,Muted,true,215);TextAt(g,F.GuideTitle,40,144,17,Ink,true,215,48);
 if(F.S.Guide<7)Button(g,F.GuideDone?"领取奖励  +20 G":"查看小提示",40,195,214,28,()=>{if(F.GuideDone)Act(F.ClaimGuide,"harvest");else Toast(F.GuideHelp);},F.GuideDone);else TextAt(g,"今天也慢慢来。",40,197,14,Muted);
 Button(g,"种田",920,100,239,34,()=>Open("fields"),true);
 if(placement!=null){Card(g,353,103,392,60);TextAt(g,"布置「"+Farm.DecorName(placement)+"」 · 点击草地放置",370,112,15,Ink,true,359);TextAt(g,"Esc 取消 · 田地、建筑和池塘不可放置",370,137,12,Muted,false,359);}else if(decorMove>=0){Card(g,340,102,440,53);TextAt(g,"移动装饰：点击空闲草地 · Esc 取消",356,117,15,Ink,true,400);}
 TextAt(g,"木屋",216,459,12,PixelArt.C("42583f"),true,90);TextAt(g,"风车磨坊",791,461,12,PixelArt.C("42583f"),true,110);
 }
 Fill(g,PixelArt.C("ebe7cf"),0,666,1200,61);TextAt(g,"壁纸田地可直接拖动；小屏幕也可在此管理。",30,684,17,Green,true,800);Button(g,"打开农田",946,678,223,35,()=>Open("fields"),true);
 Fill(g,Paper,0,727,1200,73);string[] names={"仓库","工坊","订单","建造","伙伴","手札"};string[] ids={"inventory","workshop","orders","build","pet","journal"};for(int i=0;i<6;i++){int ii=i;Button(g,names[i],26+i*157,742,143,40,()=>Open(ids[ii]),panel==ids[ii]);}TextAt(g,saveFailed?"存档失败":"已自动保存",1018,742,12,saveFailed?PixelArt.C("b36859"):Muted,false,154);TextAt(g,ShortcutKeys.Label(F.S.HotkeyMods,F.S.HotkeyKey),1018,765,10,Muted,false,167);
 if(panel!=""){using(var dim=new SolidBrush(Color.FromArgb(105,33,48,39)))g.FillRectangle(dim,0,78,1200,649);if(panel=="welcome"){hits.Clear();HitArea(0,0,1200,800,()=>{});DrawWelcome(g);}else DrawPanel(g);}
 if(F.Now<toastUntil){int y=panel==""?614:679;Fill(g,PixelArt.C("3e5849"),254,y,692,38);Center(g,toast,new Rectangle(264,y,672,38),15,Paper);}
 else if(tip!=""&&panel==""){Fill(g,PixelArt.C("3e5849"),290,619,620,30);Center(g,tip,new Rectangle(296,619,608,30),13,Paper);}
 }
 void DrawWelcome(Graphics g){Card(g,305,154,590,444);Button(g,"中文 / English",689,176,164,30,ToggleLanguage);TextAt(g,"WELCOME TO MOSSLIGHT",345,181,12,Muted,true,500);TextAt(g,"让一小片田野，住进你的桌面。",345,216,26,Ink,true,514,80);TextAt(g,"种一点小麦，听风车慢慢转。忙碌的时候，\n它会安静地生长；回到桌面，就是回家。",345,284,18,Muted,false,500,76);
 string[] title={"慢慢经营","安心离开","桌面陪伴"},desc={"收菜、加工、交订单","自动存档，离线也生长","工作时收起，不抢焦点"};for(int i=0;i<3;i++){Fill(g,PixelArt.C("ece9cf"),345+i*174,373,160,78);TextAt(g,title[i],357+i*174,385,16,Green,true,140);TextAt(g,desc[i],357+i*174,415,11,Muted,false,141);}
 Button(g,"开始我的农场",345,484,508,46,()=>{F.S.IntroSeen=true;panel="";Act(()=>"先点一块金色小麦，迎接你的第一份收成。","harvest");},true);TextAt(g,"轻点即玩  ·  无内购  ·  无需联网  ·  原创像素世界",345,550,12,Muted,false,505);}
 void DrawPanel(Graphics g){Card(g,153,104,894,553);string title=panel=="fields"?"种子与播种":panel=="inventory"?"粮仓与路边小摊":panel=="workshop"?"山谷工坊":panel=="orders"?"邻里的心愿":panel=="build"?"让农场长大":panel=="pet"?"一起生活的小伙伴":panel=="journal"?"山谷手札":"按你的节奏生活";TextAt(g,title,180,124,25,Ink,true,760);Button(g,"×",994,120,32,32,()=>{panel="";page=0;},false);Fill(g,Line,179,170,842,1);
 // The overlay owns pointer input, so farm actions beneath it cannot fire.
 var closeHit=hits[hits.Count-1];hits.Clear();HitArea(0,78,1200,649,()=>{});hits.Add(closeHit);
 if(panel=="fields")DrawFields(g);if(panel=="inventory")DrawInventory(g);if(panel=="workshop")DrawWorkshop(g);if(panel=="orders")DrawOrders(g);if(panel=="build")DrawBuild(g);if(panel=="pet")DrawPet(g);if(panel=="journal")DrawJournal(g);if(panel=="settings")DrawSettings(g);string[] navIds={"inventory","workshop","orders","build","pet","journal"};for(int ni=0;ni<6;ni++){string nav=navIds[ni];HitArea(26+ni*157,742,143,40,()=>Open(nav));}
 }
 void Pagination(Graphics g,int total,int pageSize,int y){int pages=Math.Max(1,(total+pageSize-1)/pageSize);Button(g,"上一页",760,y,80,29,()=>{page=Math.Max(0,page-1);},false,page>0);TextAt(g,(page+1)+" / "+pages,857,y+5,13,Muted,false,65);Button(g,"下一页",934,y,83,29,()=>{page=Math.Min(pages-1,page+1);},false,page<pages-1);}
 void DrawInventory(Graphics g){TextAt(g,"每块田收获 3 份。留一些原料给工坊和订单，会赚得更多。",181,185,14,Muted,false,820);var ids=Farm.Crops.Select(c=>c.Id).Concat(Farm.Recipes.Select(r=>r.Id)).Concat(new[]{"egg","milk","wool","honey"}).ToArray();for(int j=0;j<12;j++){int i=page*12+j;if(i>=ids.Length)break;string id=ids[i];int x=182+(j%3)*282,y=225+(j/3)*89;Fill(g,PixelArt.C("edead4"),x,y,271,78);PixelArt.Item(g,id,x+25,y+32,2);TextAt(g,Farm.ItemName(id),x+57,y+8,15,Ink,true,127);TextAt(g,CountText(id)+"   ·   "+Farm.Price(id)+" G",x+57,y+33,12,Muted,false,145);Button(g,"卖 1",x+204,y+9,57,27,()=>Act(()=>F.Sell(id,1),"coin"),false,F.Count(id)>0);Button(g,"全卖",x+204,y+43,57,26,()=>Act(()=>F.Sell(id,F.Count(id)),"coin"),false,F.Count(id)>0);}
 TextAt(g,"仓库无容量限制。收成可以一直留着。",182,608,12,Muted,false,550);Pagination(g,ids.Length,12,604);}
 string CountText(string id){return "库存 "+F.Count(id);}
 void DrawWorkshop(Graphics g){TextAt(g,F.ProductionPaused?"建筑施工中，全农场暂停生产，已有进度会在完工后继续。":"投入原料后依次生产，完成自动入仓。离线期间也会继续。",181,185,14,Muted,false,820);for(int j=0;j<6;j++){int i=page*6+j;if(i>=Farm.Recipes.Length)break;var r=Farm.Recipes[i];int x=182+(j%2)*423,y=223+(j/2)*124;Fill(g,PixelArt.C("edead4"),x,y,410,111);PixelArt.Item(g,r.Id,x+28,y+34,2);TextAt(g,r.Name,x+65,y+10,18,Ink,true,199);TextAt(g,Farm.BuildingName(r.Building)+" · "+Farm.TimeText(r.Seconds),x+65,y+37,12,Muted,false,330);TextAt(g,string.Join("  ",r.Inputs.Select(p=>Farm.ItemName(p.Key)+" "+F.Count(p.Key)+"/"+p.Value)),x+13,y+66,13,Muted,false,382);var q=F.S.Queues.ContainsKey(r.Building)?F.S.Queues[r.Building]:new List<Job>();string status=F.ProductionPaused?"施工期间暂停":!F.Has(r.Building)?"尚未建造":q.Count==0?"工坊空闲":q.Count+" 份排队 · "+Farm.TimeText(F.ProductionRemaining(q[0].Ready));TextAt(g,status,x+13,y+89,11,Green,false,377);Button(g,F.Level<r.Level?"Lv."+r.Level:"制作",x+308,y+12,88,33,()=>Act(()=>F.Craft(r.Id)),true,F.Has(r.Building)&&F.Level>=r.Level&&!F.ProductionPaused);}
 TextAt(g,"Lv.1 建筑：2 槽 · Lv.2：3 槽 · Lv.3：4 槽、加速 10%",182,611,12,Muted,false,570);Pagination(g,Farm.Recipes.Length,6,604);}
 void DrawOrders(Graphics g){TextAt(g,"新鲜的收成，送给熟悉的人。订单永不过期，完成后刷新。",181,185,14,Muted,false,820);for(int i=0;i<3;i++){int ii=i;var o=F.S.OrdersList[i];int x=182+i*282;Card(g,x,225,267,322,PixelArt.C("eee9d0"));Badge(g,"邻里订单  0"+(i+1),x+16,241,112,Green);TextAt(g,o.Person,x+16,281,18,Ink,true,235);TextAt(g,o.Text,x+16,314,13,Muted,false,231,52);int y=379;foreach(var p in o.Items){PixelArt.Item(g,p.Key,x+27,y+10,1);TextAt(g,Farm.ItemName(p.Key),x+47,y,14,Ink,false,129);TextAt(g,F.Count(p.Key)+" / "+p.Value,x+171,y,14,F.Count(p.Key)>=p.Value?Green:PixelArt.C("b47556"),true,85);y+=32;}TextAt(g,"+"+o.Coins+" G    +"+o.Xp+" XP",x+17,470,15,Gold,true,237);Button(g,F.CanOrder(o)?"打包交付":"等待食材",x+16,504,235,30,()=>Act(()=>F.Deliver(ii),"coin"),true,F.CanOrder(o));}
 Button(g,"领取今日来信  +35 G",182,579,251,40,()=>Act(F.Daily,"coin"),true,F.S.DailyClaim!=DateTime.Today.ToString("yyyy-MM-dd"));Button(g,F.Has("station")?"列车发货":"列车货运 · Lv.10",451,579,250,40,()=>{Act(F.Train,"coin");trainUntil=animation+15;},false,F.Has("station"));TextAt(g,F.Has("station")?"面包 5 / 牛奶 6 / 果酱 2\n奖励 700–900 G + 25 XP":"每一天都值得一份小礼物。",720,580,12,Muted,false,290,58);}
 void DrawBuild(Graphics g){if(F.ProductionPaused)TextAt(g,"施工中：田地、动物与工坊暂停生产。",655,190,12,Gold,true,355);Button(g,"建筑与扩建",182,184,157,30,()=>{tab="";page=0;},tab=="");Button(g,"布置农场",351,184,140,30,()=>{tab="decor";page=0;},tab=="decor");Button(g,"动物伙伴",503,184,140,30,()=>{tab="animals";page=0;},tab=="animals");
 if(tab=="decor"){string[] types={"flowers","fence","lamp","bench","tree","fountain"};for(int i=0;i<6;i++){string type=types[i];int x=182+(i%3)*282,y=234+(i/3)*141;Fill(g,PixelArt.C("e7e6cd"),x,y,268,127);var st=g.Save();g.TranslateTransform(x+43,y+(type=="tree"?101:74));g.ScaleTransform(type=="tree"?1f:1.5f,type=="tree"?1f:1.5f);PixelArt.Decor(g,type,0,0,false);g.Restore(st);TextAt(g,Farm.DecorName(type),x+98,y+15,18,Ink,true,156);TextAt(g,Farm.DecorCost(type)+" 金币",x+99,y+46,13,Gold,false,135);Button(g,"选择位置",x+99,y+79,149,30,()=>{placement=type;panel="";watering=false;Toast("点击空闲草地放置，Esc 取消。放下时才会扣金币。");},true);}
 TextAt(g,"点击已有装饰可移动；右键收回返还一半金币。最多放置 128 件。",182,544,13,Muted,false,837);TextAt(g,"已布置 "+F.S.Decorations.Count+" / 128 件",182,578,14,Green,true,300);return;}
 if(tab=="animals"){string[] kinds={"chicken","cow","sheep","bee"};string[] labels={"小鸡","奶牛","绵羊","蜜蜂"},info={"建鸡舍赠送 · 鸡蛋 / 3分钟","建牛棚赠送 · 牛奶 / 10分钟","Lv.6 · 320 G · 羊毛 / 15分钟","Lv.8 · 400 G · 蜂蜜 / 15分钟"};for(int i=0;i<4;i++){int ii=i;string kind=kinds[i];int x=182+(i%2)*423,y=236+(i/2)*151;Fill(g,PixelArt.C("e7e6cd"),x,y,410,133);var st=g.Save();g.TranslateTransform(x+48,y+82);g.ScaleTransform(2,2);PixelArt.Animal(g,0,0,kind,animation,false);g.Restore(st);TextAt(g,labels[i],x+102,y+12,19,Ink,true,280);TextAt(g,info[i],x+102,y+45,12,Muted,false,298);bool owned=F.S.Animals.Any(a=>a.Type==kind);Button(g,owned?"已入住":i<2?"建造住所":"邀请入住",x+102,y+83,285,30,()=>{if(owned){Toast("去「伙伴」面板喂食和收集产物。");return;}Act(()=>ii==0?F.BuyBuilding("coop"):ii==1?F.BuyBuilding("barn"):F.BuyAnimal(kind));},!owned);}
 TextAt(g,"每次喂食需要 1 份饲料或 3 份小麦。动物不会生病或离开。",182,571,13,Muted,false,810);return;}
 for(int i=0;i<Farm.BuildingIds.Length;i++){string id=Farm.BuildingIds[i];int x=182+(i%3)*282,y=230+(i/3)*84;bool owned=F.Has(id),busy=F.S.Construction.ContainsKey(id);Fill(g,PixelArt.C("edead4"),x,y,267,79);TextAt(g,Farm.BuildingNames[i]+(owned?" · Lv."+F.S.Buildings[id]:""),x+12,y+5,14,Ink,true,249);string cost=busy?L.T("施工中")+" · "+Farm.TimeText(F.S.Construction[id].Ready-F.Now):owned&&F.S.Buildings[id]>=3?L.T("已满级"):(owned?F.UpgradeCost(id):Farm.BuildingCosts[i])+" G · "+Farm.TimeText(F.BuildSeconds(id,owned?F.S.Buildings[id]+1:1));TextAt(g,cost,x+12,y+29,11,Muted,false,249);Button(g,busy?"施工中":owned?"升级 / 查看":"建造",x+12,y+50,242,23,()=>Act(()=>F.BuyBuilding(id)),!owned,F.CanBuild(id));}

 Fill(g,PixelArt.C("dfe5c7"),182,573,833,60);TextAt(g,"土地  "+F.S.Plots.Count+" / 81 块",196,583,16,Green,true,239);TextAt(g,F.S.Land>=7?"山谷已经完全展开":"下一片农田 · "+F.ExpandCost+" G · Lv."+F.ExpandLevel,196,608,11,Muted,false,550);Button(g,F.S.Land>=7?"全部开垦":"扩建土地",755,585,243,34,()=>Act(F.Expand,"harvest"),true,F.S.Land<7);}
 void DrawPet(Graphics g){Card(g,181,190,314,425,PixelArt.C("e6e6cb"));var st=g.Save();g.TranslateTransform(327,305);g.ScaleTransform(5,5);PixelArt.Cat(g,0,0,animation,F.S.Pet=="dog",false,1,F.Now-F.S.LastPet<4);g.Restore(st);TextAt(g,F.S.Pet=="cat"?"团子 · 橘猫":"豆豆 · 柴犬",206,334,24,Ink,true,271);TextAt(g,"好感度  "+F.S.PetLove+"  /  "+(F.S.PetLove<20?"初识":F.S.PetLove<80?"亲密":"形影不离"),206,374,15,Green,true,270);TextAt(g,F.S.PetLove>=20?"已达成成就：最好的朋友":"20 好感度获得亲密成就奖励",206,407,12,Muted,false,270);Button(g,"摸摸它  +2",206,447,263,35,()=>Act(F.Pet));Button(g,"喂小零食  +5",206,494,263,35,()=>Act(F.GiftPet));Button(g,F.S.Pet=="cat"?"换成柴犬":"换成橘猫",206,551,263,34,()=>{F.S.Pet=F.S.Pet=="cat"?"dog":"cat";Act(()=>"新的陪伴外观已换好，好感度保留。");});
 TextAt(g,F.ProductionPaused?"施工中：动物产出暂停":"牧场里的小日常",522,192,20,Ink,true,470);if(F.S.Animals.Count==0){TextAt(g,"这里还很安静。\n\nLv.2 在「建造」里添一间鸡舍，\n第一只小鸡就会搬过来。",523,250,17,Muted,false,461,190);Button(g,"去看看鸡舍",523,459,469,38,()=>{panel="build";tab="";},true);}else for(int i=0;i<F.S.Animals.Count;i++){int ii=i;var a=F.S.Animals[i];int y=232+i*90;Fill(g,PixelArt.C("edead4"),521,y,491,78);var state=g.Save();g.TranslateTransform(554,y+51);g.ScaleTransform(1.6f,1.6f);PixelArt.Animal(g,0,0,a.Type,animation,false);g.Restore(state);string title=a.Type=="chicken"?"小鸡":a.Type=="cow"?"奶牛":a.Type=="sheep"?"绵羊":"蜜蜂";TextAt(g,title,592,y+11,17,Ink,true,205);TextAt(g,!a.Fed?"等你喂食":a.Ready<=F.Now?"产物可以收集了":Farm.TimeText(a.Ready-F.Now),592,y+41,12,Muted,false,211);Button(g,!a.Fed?"喂食":a.Ready<=F.Now?"收集":"休息中",839,y+20,155,32,()=>Act(()=>F.AnimalAction(ii),"harvest"),true,(!a.Fed||a.Ready<=F.Now)&&!F.ProductionPaused);}
 TextAt(g,"抚摸每分钟增加一次好感；零食每 5 分钟一次。",520,619,11,Muted,false,501);}
 void DrawJournal(Graphics g){TextAt(g,"不必每天打卡。你离开多久，回来的时候这里都欢迎你。",181,188,14,Muted,false,833);Fill(g,PixelArt.C("e2e6cb"),182,228,832,89);TextAt(g,F.GuideTitle,200,242,20,Ink,true,604);TextAt(g,F.GuideHelp,200,278,13,Muted,false,609);Button(g,F.GuideDone?"领取 +20 G":"慢慢来",817,249,179,41,()=>Act(F.ClaimGuide,"coin"),F.GuideDone,F.GuideDone);
 string[] ids={"first","maker","orders","harvest","friend","land","rich"},names={"第一缕麦香","手作时光","山谷好邻居","丰收的日子","最好的朋友","更大的世界","小镇的梦想"},desc={"收获第 1 块田","完成第 1 份加工","完成 5 张订单","收获 50 块田","达到 20 好感度","第一次扩建土地","累计赚取 3000 金币"};for(int i=0;i<7;i++){int x=182+(i%2)*423,y=335+(i/2)*64;bool done=F.S.Achievements.Contains(ids[i]);Fill(g,done?PixelArt.C("dce3c5"):PixelArt.C("ecead7"),x,y,410,54);TextAt(g,done?"✓":"○",x+12,y+10,24,done?Green:Muted,true,40);TextAt(g,names[i],x+53,y+6,15,Ink,true,341);TextAt(g,desc[i]+(done?" · 已达成":""),x+54,y+30,11,Muted,false,340);}
 TextAt(g,"收获 "+F.S.Harvests+" 次  /  加工 "+F.S.Made+" 份  /  完成订单 "+F.S.Orders+" 张",182,612,13,Muted,false,833);}
 void DrawSettings(Graphics g){
 TextAt(g,"实时桌面风景",183,188,20,Green,true,525);Button(g,F.S.Language=="en"?"Language: English":"语言 / Language：简体中文",739,184,275,31,ToggleLanguage);
 TextAt(g,"独立桌面农场 · 直接点击种植和收获，拖动即可布置。",183,224,13,Muted,false,832);
 Button(g,"设为桌面背景",183,257,262,36,()=>SetDesktop(true),true);Button(g,"布置桌面",461,257,262,36,ShowWallpaperPreview);Button(g,"恢复原桌面",739,257,275,36,StopWallpaper);
 TextAt(g,"自由活动 · 整个屏幕",183,308,14,Green,true,265);Button(g,"屏幕："+(F.S.Monitor+1)+" / "+Screen.AllScreens.Length,461,305,262,32,()=>{if(Screen.AllScreens.Length<2)return;bool active=engineHost!=null&&engineHost.Active;if(engineHost!=null){engineHost.Dispose();engineHost=null;}F.S.Monitor=(F.S.Monitor+1)%Screen.AllScreens.Length;if(active)EnsureWallpaper();SaveGame();});Button(g,"呼唤小伙伴",739,305,275,32,()=>{if(engineHost!=null)engineHost.CallAnimals();if(wallpaper!=null)wallpaper.CallAnimals();if(wallpaperPreview!=null)wallpaperPreview.CallAnimals();Toast("小伙伴们正在慢慢回家。");});
 TextAt(g,"氛围与声音",183,355,18,Green,true,832);
 Button(g,"天气："+F.S.Weather,183,389,262,35,()=>{string[] options={"自动","晴天","雨天","雪天"};F.S.Weather=options[(Array.IndexOf(options,F.S.Weather)+1)%4];Act(()=>"天气已切换为"+F.S.Weather+"。自动天气是本地模拟。");});Button(g,"轻音乐："+(F.S.Music?"开":"关"),461,389,262,35,()=>{F.S.Music=!F.S.Music;SetMusic(F.S.Music);SaveGame();});Button(g,"音效："+(F.S.Sound?"开":"关"),739,389,275,35,()=>{F.S.Sound=!F.S.Sound;Act(()=>"音效已"+(F.S.Sound?"开启":"关闭"));});
 Button(g,"昼夜："+F.S.Lighting,183,440,262,34,()=>{string[] modes={"跟随时间","白天","夜晚"};F.S.Lighting=modes[(Array.IndexOf(modes,F.S.Lighting)+1)%3];Act(()=>"昼夜已设为"+F.S.Lighting+"。");});Button(g,"安静 / 省电模式："+(F.S.Quiet?"开":"关"),461,440,553,34,()=>{F.S.Quiet=!F.S.Quiet;Act(()=>"安静模式降低动画帧率，作物照常生长。");});
 Button(g,"快捷键："+ShortcutKeys.Label(F.S.HotkeyMods,F.S.HotkeyKey),183,493,400,34,ChooseShortcut);TextAt(g,"农田在独立页面，扩建不会占用桌面道路。",183,541,13,Muted,false,833,35);
 Button(g,F.S.Language=="en"?"Save and exit":"保存并退出",183,588,262,28,ExitGame);TextAt(g,Farm.MaintenanceBuild?"Mosslight Maintenance v1.1":"Mosslight v1.1",183,629,12,Muted,false,700);Button(g,"打开存档文件夹",755,588,259,28,()=>System.Diagnostics.Process.Start("explorer.exe",Path.GetDirectoryName(SavePath)));
 }
 bool FreeSpot(Point p,int skip){if(p.X<61||p.X>542||p.Y<158||p.Y>273)return false;if(new Rectangle(212,128,168,150).Contains(p)||new Rectangle(69,111,110,99).Contains(p)||new Rectangle(386,100,76,111).Contains(p)||new Rectangle(443,195,116,83).Contains(p)||new Rectangle(49,207,72,64).Contains(p)||new Rectangle(140,214,63,67).Contains(p)||new Rectangle(389,224,57,56).Contains(p))return false;for(int i=0;i<F.S.Decorations.Count;i++)if(i!=skip){var d=F.S.Decorations[i];if(Math.Abs(d.X-p.X)<22&&Math.Abs(d.Y-p.Y)<19)return false;}return true;}
 int PlotAt(Point p){return -1;}
 void WorldClick(Point p){if(placement!=null){if(!FreeSpot(p,-1)){Toast("这里留给田地、建筑或道路吧。换一块空闲草地。");return;}string kind=placement;int count=F.S.Decorations.Count;Act(()=>F.BuyDecoration(kind,p.X,p.Y));if(F.S.Decorations.Count>count)placement=null;return;}if(decorMove>=0){if(!FreeSpot(p,decorMove)){Toast("这处位置放不下装饰，请换一块草地。");return;}if(decorMove<F.S.Decorations.Count){F.S.Decorations[decorMove].X=p.X;F.S.Decorations[decorMove].Y=p.Y;}decorMove=-1;SaveGame();Toast("装饰已移动。");return;}
 int plot=PlotAt(p);if(plot>=0){if(plot>=F.S.Plots.Count){Open("build");Toast("还未开垦的土地，可以在这里扩建。");return;}var crop=F.S.Plots[plot];if(crop.Crop=="")Act(()=>F.Plant(plot,selected));else if(crop.Ready<=F.Now)Act(()=>F.Harvest(plot),"harvest");else if(watering)Act(()=>F.Water(plot),"water");else Toast(Farm.ItemName(crop.Crop)+" · "+Farm.TimeText(crop.Ready-F.Now)+"后成熟"+(crop.Watered?" · 已浇水":" · 按 W 可切换浇水"));return;}
 var pet=PixelArt.PetPosition(animation);if(Math.Abs(p.X-pet.X)<20&&Math.Abs(p.Y-pet.Y)<25){Act(F.Pet);return;}for(int i=F.S.Decorations.Count-1;i>=0;i--){var d=F.S.Decorations[i];if(Math.Abs(p.X-d.X)<16&&p.Y>=d.Y-(d.Type=="tree"?60:25)&&p.Y<=d.Y+8){decorMove=i;if(desktop)SetDesktop(false);Toast("点击空闲草地移动装饰；Esc 取消。");return;}}
 if((F.Has("dairy")&&new Rectangle(263,71,43,48).Contains(p))||(F.Has("loom")&&new Rectangle(205,66,43,48).Contains(p))||(F.Has("sugarhouse")&&new Rectangle(321,71,43,48).Contains(p))||(F.Has("preserves")&&new Rectangle(478,119,43,48).Contains(p))){Open("workshop");if(p.X<252||p.X>315)page=1;return;}if(F.Has("bakery")&&new Rectangle(39,178,80,88).Contains(p)){Open("workshop");return;}if(new Rectangle(387,93,74,110).Contains(p)){Open("workshop");return;}if(new Rectangle(72,105,108,96).Contains(p)){Open("journal");return;}if(p.X<206&&p.Y>213){Open(F.Has("coop")?"pet":"build");return;}if(p.X>390&&p.X<443&&p.Y>226){Open(F.Has("barn")?"pet":"build");return;}Toast("让风车慢慢转，今天也慢慢来。");}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);mouseLogical=new Point((int)(e.X*(desktop?600.0:1200)/ClientSize.Width),(int)(e.Y*(desktop?360.0:800)/ClientSize.Height));mouseWorld=desktop?mouseLogical:new Point(mouseLogical.X/2,(mouseLogical.Y-78)/2);hoverPlot=panel==""?PlotAt(mouseWorld):-1;tip="";foreach(var h in hits)if(h.Bounds.Contains(mouseLogical)&&h.Hint!="")tip=h.Hint;Cursor=(hoverPlot>=0||hits.Any(h=>h.Bounds.Contains(mouseLogical)))?Cursors.Hand:Cursors.Default;}
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);OnMouseMove(e);if(e.Button==MouseButtons.Right&&panel==""){for(int i=F.S.Decorations.Count-1;i>=0;i--){var d=F.S.Decorations[i];if(Math.Abs(mouseWorld.X-d.X)<16&&Math.Abs(mouseWorld.Y-d.Y)<25){F.S.Coins+=Farm.DecorCost(d.Type)/2;F.S.Decorations.RemoveAt(i);decorMove=-1;Act(()=>"装饰已收回，返还一半金币。","coin");return;}}watering=!watering;Toast(watering?"浇水工具已选中。":"切回种植工具。");return;}if(e.Button!=MouseButtons.Left)return;for(int i=hits.Count-1;i>=0;i--)if(hits[i].Bounds.Contains(mouseLogical)){var action=hits[i].Action;action();Invalidate();return;}}
 protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);if(e.KeyCode==Keys.Escape){if(panel=="welcome"){F.S.IntroSeen=true;SaveGame();}panel="";placement=null;decorMove=-1;Invalidate();return;}if(panel!="")return;if(e.KeyCode>=Keys.D1&&e.KeyCode<=Keys.D9){int i=(int)e.KeyCode-(int)Keys.D1;if(F.Level>=Farm.Crops[i].Level){selected=Farm.Crops[i].Id;F.S.SelectedSeed=selected;SaveGame();watering=false;Toast("已选择"+Farm.Crops[i].Name);}}if(e.KeyCode==Keys.H)Act(F.HarvestAll,"harvest");if(e.KeyCode==Keys.W){watering=!watering;Toast(watering?"已选择浇水工具。":"已选择种植工具。");}if(e.KeyCode==Keys.B)Open("inventory");if(e.KeyCode==Keys.O)Open("orders");Invalidate();}
 void Play(string name){if(!F.S.Sound||F.S.Music)return;try{string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",name+".wav");if(!File.Exists(path))return;if(!sounds.ContainsKey(name))sounds[name]=new SoundPlayer(path);sounds[name].Play();}catch{}}
 void SetMusic(bool on){try{if(musicPlayer!=null){musicPlayer.Stop();musicPlayer.Dispose();musicPlayer=null;}if(on){string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","meadow.wav");if(File.Exists(path)){musicPlayer=new SoundPlayer(path);musicPlayer.PlayLooping();}}}catch{Toast("音乐暂时无法播放。");}}
 protected override void Dispose(bool disposing){if(disposing&&!disposed){disposed=true;if(engineHost!=null){engineHost.Dispose();engineHost=null;}timer.Stop();timer.Dispose();if(wallpaper!=null){wallpaper.Close();wallpaper=null;}if(wallpaperPreview!=null){wallpaperPreview.Close();wallpaperPreview=null;}UnregisterHotKey(Handle,1);tray.Visible=false;tray.Dispose();if(musicPlayer!=null){musicPlayer.Stop();musicPlayer.Dispose();}foreach(var s in sounds.Values)s.Dispose();foreach(var f in fonts.Values)f.Dispose();ownIcon.Dispose();}base.Dispose(disposing);}
}
}
