using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Drawing;
using System.Windows.Forms;
using System.Web.Script.Serialization;
namespace DesktopFarm {
public class LiveFarmHost:IDisposable {
 NativeDesktop native;bool qaSession;DateTime lastAck=DateTime.UtcNow,lastRecovery=DateTime.MinValue;
 readonly Control dispatcher;readonly Farm farm;readonly Action changed;readonly Action<string> open;readonly string folder;readonly JavaScriptSerializer json=new JavaScriptSerializer();TcpListener server;WallpaperForm scene;string token;int port;bool stopped;long received,rendered,interactions,nativeDown,nativeMove,nativeUp;DateTime lastLog=DateTime.MinValue;public bool Active;public string Status="Starting";string requestedPanel="";int panelRevision;
 public LiveFarmHost(Control ui,Farm f,Action save,Action<string> onOpen,string savePath){qaSession=Path.GetFileName(savePath)=="qa-save.json";dispatcher=ui;farm=f;changed=save;open=onOpen;folder=qaSession?Path.Combine(Path.GetDirectoryName(savePath),"web-wallpaper"):Path.Combine(Path.GetDirectoryName(savePath),"desktop");}
 public bool DesktopReady {get{return native!=null&&native.Attached&&received>0&&(DateTime.UtcNow-lastAck).TotalSeconds<15;}}
 public static bool ShouldRecover(double secondsWithoutFrames,double secondsSinceRepair,bool desktopVisible,bool ownWallpaper){return secondsWithoutFrames>30&&secondsSinceRepair>120&&desktopVisible&&ownWallpaper;}
 public void RequestRepair(bool force){if(stopped)return;lastRecovery=DateTime.UtcNow;if(native==null||native.IsDisposed||native.Failed){if(native!=null)native.Dispose();CreateDesktop();}else{if(force)native.RestoreDesktop();else native.Reload();}}
 public void Pulse(){if(stopped||native==null)return;if(native.IsDisposed||native.Failed){if((DateTime.UtcNow-lastRecovery).TotalSeconds>15)RequestRepair(true);Log();return;}native.Pulse();if(ShouldRecover((DateTime.UtcNow-lastAck).TotalSeconds,(DateTime.UtcNow-lastRecovery).TotalSeconds,DesktopHost.DesktopForeground,true))RequestRepair(false);Log();}
 public void Start(){Directory.CreateDirectory(folder);token=Guid.NewGuid().ToString("N");server=new TcpListener(IPAddress.Loopback,0);server.Start();port=((IPEndPoint)server.LocalEndpoint).Port;scene=new WallpaperForm(farm,name=>{requestedPanel=name=="journal"?"orders":name=="pet"?"animals":name;panelRevision++;},()=>{interactions++;changed();},true);scene.TraceInput=true;scene.ExternalHud=true;scene.EditMode=false;scene.ClientSize=new Size(960,540);scene.CreateControl();string url="http://127.0.0.1:"+port+"/"+token+"/";File.WriteAllText(Path.Combine(folder,"index.html"),Page.Replace("<head>","<head><base href='"+url+"'>"));var worker=new Thread(Accept){IsBackground=true};worker.Start();CreateDesktop();Active=true;Status="Starting independent desktop";Log();}
 void CreateDesktop(){string url="http://127.0.0.1:"+port+"/"+token+"/";native=new NativeDesktop(url,Path.Combine(folder,"browser-profile"),farm.S.Monitor,(x,y)=>scene.NativeHit(x,y),s=>{Status=s;RuntimeLog.Write(s);},(phase,x,y)=>{if(phase=="down")nativeDown++;if(phase=="move")nativeMove++;if(phase=="up")nativeUp++;scene.ClientInput(phase,x,y);Log();},Program.NativePreview);native.Show();}
 void Accept(){while(!stopped){try{var client=server.AcceptTcpClient();ThreadPool.QueueUserWorkItem(s=>Serve((TcpClient)s),client);}catch{if(stopped)return;}}}
 object UI(Func<object> action){if(stopped||dispatcher.IsDisposed)return null;return dispatcher.Invoke(action);}
 void Serve(TcpClient client){using(client){try{client.ReceiveTimeout=3000;client.SendTimeout=3000;var stream=client.GetStream();var header=new MemoryStream();int b,matched=0;while(header.Length<16384&&(b=stream.ReadByte())>=0){header.WriteByte((byte)b);if((matched==0||matched==2)&&b==13)matched++;else if((matched==1||matched==3)&&b==10)matched++;else matched=0;if(matched==4)break;}string raw=Encoding.ASCII.GetString(header.ToArray());string[] lines=raw.Split(new[]{"\r\n"},StringSplitOptions.None);string[] first=lines[0].Split(' ');if(first.Length<2)return;string route=first[1];string prefix="/"+token+"/";if(!route.StartsWith(prefix,StringComparison.Ordinal)){Reply(stream,403,"text/plain",Encoding.UTF8.GetBytes("Forbidden"));return;}route=route.Substring(prefix.Length).Split('?')[0];int length=0;foreach(var line in lines)if(line.StartsWith("Content-Length:",StringComparison.OrdinalIgnoreCase))int.TryParse(line.Substring(15).Trim(),out length);if(length<0||length>4096)return;byte[] body=new byte[length];int offset=0;while(offset<length){int n=stream.Read(body,offset,length-offset);if(n<=0)return;offset+=n;}byte[] result;string type="text/plain";
   if(route==""){type="text/html; charset=utf-8";result=Encoding.UTF8.GetBytes(Page);}
   else if(route=="state"){type="application/json; charset=utf-8";result=(byte[])UI(()=>Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(DesktopHud.State(farm,scene,requestedPanel,panelRevision,!qaSession&&StartupManager.Enabled,!qaSession))));}
   else if(route=="command"&&first[0]=="POST"){var command=new JavaScriptSerializer().Deserialize<DesktopHud.Command>(Encoding.UTF8.GetString(body));UI(()=>{string message="";if(command!=null&&command.action=="shortcut-dialog"){dispatcher.BeginInvoke((Action)(()=>((GameForm)dispatcher).ChooseShortcut()));}else if(command!=null&&command.action=="shortcut"){message=((GameForm)dispatcher).ChangeShortcut(command.id);}else if(command!=null&&command.action=="startup"){if(!qaSession)StartupManager.SetEnabled(command.id=="on");}else if(command!=null&&command.action=="native-attach"&&qaSession&&native!=null)native.AttachNow();else if(command!=null&&command.action=="repair")RequestRepair(true);else message=DesktopHud.Apply(farm,scene,command);if(message!="")scene.Announce(message);interactions++;changed();Log();return true;});result=Encoding.UTF8.GetBytes("ok");}
   else if(route.StartsWith("sprite/")){string id=Uri.UnescapeDataString(route.Substring(7));type="image/png";result=(byte[])UI(()=>{using(var bitmap=new Bitmap(48,48))using(var g=Graphics.FromImage(bitmap))using(var memory=new MemoryStream()){g.Clear(Color.Transparent);if(id.StartsWith("decor:")){string kind=id.Substring(6);g.TranslateTransform(24,42);if(kind=="tree")g.ScaleTransform(.5f,.5f);PixelArt.Decor(g,kind,0,0,false);}else PixelArt.Item(g,id,24,24,2);bitmap.Save(memory,System.Drawing.Imaging.ImageFormat.Png);return memory.ToArray();}});}
   else if(route.StartsWith("building/")||route.StartsWith("map/")){type="image/png";result=(byte[])UI(()=>{string id=route.Substring(route.IndexOf('/')+1);using(var memory=new MemoryStream()){if(route.StartsWith("map/")){using(var bitmap=WorldMap.Preview(id))bitmap.Save(memory,System.Drawing.Imaging.ImageFormat.Png);}else using(var bitmap=new Bitmap(128,128))using(var g=Graphics.FromImage(bitmap)){g.Clear(Color.Transparent);BuildingArt.ForFarm(g,farm,64,112,id,0);if(!farm.Has(id)&&!farm.S.Construction.ContainsKey(id)){if(id=="cabin")PixelArt.Cabin(g,64,112,false,0);else if(id=="mill")PixelArt.Mill(g,64,112,0,false);else if(id=="bakery")BuildingArt.Bakery(g,64,112,false);else BuildingArt.Draw(g,64,112,id,false);}bitmap.Save(memory,System.Drawing.Imaging.ImageFormat.Png);}return memory.ToArray();}});}
   else if(route=="frame"){type="image/png";result=(byte[])UI(()=>{using(var bitmap=scene.SceneSnapshot(960,540,true))using(var memory=new MemoryStream()){bitmap.Save(memory,System.Drawing.Imaging.ImageFormat.Png);rendered++;return memory.ToArray();}});}
   else if(route=="input"&&first[0]=="POST"){var data=new JavaScriptSerializer().Deserialize<Input>(Encoding.UTF8.GetString(body));UI(()=>{if(data!=null){scene.ClientInput(data.phase,Math.Max(0,Math.Min(1,data.x)),Math.Max(0,Math.Min(1,data.y)));Log();}return true;});result=Encoding.UTF8.GetBytes("ok");}
   else if(route=="ack"&&first[0]=="POST"){Interlocked.Increment(ref received);lastAck=DateTime.UtcNow;Status="Live wallpaper connected";UI(()=>{Log();return true;});result=Encoding.UTF8.GetBytes("ok");}
   else{Reply(stream,404,"text/plain",Encoding.UTF8.GetBytes("Not found"));return;}if(result!=null)Reply(stream,200,type,result,route.StartsWith("sprite/"));
  }catch(Exception e){if(!stopped)Status=e.Message;}}}
 public class Input {public string phase {get;set;}public double x {get;set;}public double y {get;set;}}
 static void Reply(Stream stream,int code,string type,byte[] bytes,bool cache=false){byte[] header=Encoding.ASCII.GetBytes("HTTP/1.1 "+code+" OK\r\nContent-Type: "+type+"\r\nContent-Length: "+bytes.Length+"\r\nCache-Control: "+(cache?"private, max-age=3600":"no-store")+"\r\nAccess-Control-Allow-Origin: *\r\nConnection: close\r\nX-Content-Type-Options: nosniff\r\n\r\n");stream.Write(header,0,header.Length);stream.Write(bytes,0,bytes.Length);}
 void Log(){if((DateTime.UtcNow-lastLog).TotalSeconds<2)return;lastLog=DateTime.UtcNow;File.WriteAllText(Path.Combine(folder,"live-status.json"),json.Serialize(new{nativeDown=nativeDown,nativeMove=nativeMove,nativeUp=nativeUp,backend="Independent WebView2",attached=native!=null&&native.Attached,status=Status,framesRendered=rendered,framesAcknowledged=received,gameInteractions=interactions,updated=DateTime.UtcNow.ToString("o")}));}
 public void CallAnimals(){if(scene!=null)scene.CallAnimals();}
 public void ShowPanel(string name){requestedPanel=name;panelRevision++;}
 public void Dispose(){if(stopped)return;stopped=true;Active=false;if(native!=null){native.Dispose();native=null;}if(server!=null)server.Stop();if(scene!=null)scene.Dispose();}
 static string Page {get{return File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","desktop.html"));}}
}
}
