using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using System.Collections.Generic;

namespace DesktopFarm {
static class Program { internal static EventWaitHandle OpenSignal,DesktopSignal,QuitSignal;internal static bool StartupLaunch,NativePreview,DesktopLaunch,ManageLaunch;
#if MAINTENANCE_BUILD
 const string BuildSuffix="Maintenance";
#else
 const string BuildSuffix="Player";
#endif
 [DllImport("user32.dll")]static extern bool SetProcessDPIAware();
 [STAThread]static void Main(string[] args){try{MainCore(args);}catch(Exception e){RuntimeLog.Write("Fatal: "+e);if(!args.Contains("--startup"))MessageBox.Show(e.Message,"Mosslight");Environment.ExitCode=1;}}
 static void MainCore(string[] args){RuntimeLog.Write("Boot: entering UI initialization");SetProcessDPIAware();Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);RuntimeLog.Write("Boot: UI initialized");
 ManageLaunch=args.Contains("--manage");DesktopLaunch=!args.Contains("--manage")&&!args.Contains("--qa");
#if MAINTENANCE_BUILD
 DesktopLaunch=DesktopLaunch&&args.Contains("--desktop");
#endif
 NativePreview=args.Contains("--desktop-preview");StartupLaunch=args.Contains("--startup");if(args.Length>1&&args[0]=="--set-autostart"){StartupManager.SetEnabled(args[1]=="on");return;}
 if(args.Contains("--check-runtime")){Environment.ExitCode=NativeDesktop.RuntimeAvailable?0:2;return;}if(args.Contains("--quit")){EventWaitHandle quit;if(EventWaitHandle.TryOpenExisting("Local\\MosslightFarm-"+BuildSuffix+"-Quit",out quit))using(quit)quit.Set();return;}
 if(args.Length>0&&args[0]=="--self-test"){
#if MAINTENANCE_BUILD
 MaintenanceTests.Run(args.Length>1?args[1]:Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-results"));
#else
 Tests.Run(args.Length>1?args[1]:Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-results"));
#endif
 return;}
 if(args.Length>0&&args[0]=="--render"){Render(args[1]);return;} if(args.Length>1&&args[0]=="--verify-desktop"){VerifyDesktop(args[1]);return;}
 bool qa=args.Length>0&&args[0]=="--qa";string path=qa?Path.Combine(args[1],"qa-save.json"):PlayerStorage.SavePath;
 if(!qa)RuntimeLog.Write(StartupLaunch?"Launch: Windows startup":"Launch: manual");
 string signalPrefix=qa?"Local\\MosslightFarm-QA":"Local\\MosslightFarm-"+BuildSuffix;DesktopSignal=new EventWaitHandle(false,EventResetMode.AutoReset,signalPrefix+"-Desktop");QuitSignal=new EventWaitHandle(false,EventResetMode.AutoReset,signalPrefix+"-Quit");
 OpenSignal=new EventWaitHandle(false,EventResetMode.AutoReset,signalPrefix+"-Open");bool created;using(var mutex=new Mutex(true,qa?"MosslightFarm-QA":"MosslightFarm-"+BuildSuffix,out created)){if(!created){if(DesktopLaunch||StartupLaunch)DesktopSignal.Set();else OpenSignal.Set();return;}var farm=new Farm(Farm.UtcNow);farm.Load(path);if(StartupLaunch||DesktopLaunch){farm.S.WallpaperEnabled=true;farm.S.Desktop=true;farm.S.IntroSeen=true;}if(farm.LoadNotice.StartsWith("存档和备份"))path=Path.Combine(Path.GetDirectoryName(path),"recovered-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json");
 Application.ThreadException+=(s,e)=>{try{File.AppendAllText(Path.Combine(Path.GetDirectoryName(path),"error.log"),DateTime.Now+" "+e.Exception+Environment.NewLine);}catch{}MessageBox.Show(L.T("遇到一个小问题，农场会继续运行。\n")+e.Exception.Message,L.T("苔光农场"));};Application.Run(new GameForm(farm,path,false));}
 }
 static void VerifyDesktop(string path){Directory.CreateDirectory(path);var f=new Farm(Farm.UtcNow);var lines=new List<string>();IntPtr surface=IntPtr.Zero;try{using(var scene=new WallpaperForm(f,s=>{},()=>{},false))using(var timer=new System.Windows.Forms.Timer()){timer.Interval=800;int step=0;scene.Shown+=(s,e)=>{if(!scene.Bind())throw new InvalidOperationException(scene.HostDetail);surface=scene.Handle;timer.Start();};timer.Tick+=(s,e)=>{try{lines.Add(DesktopHost.Verify(scene));if(scene.PresentedFrames==0||scene.RenderError!="")throw new InvalidOperationException("No live frames: "+scene.RenderError);lines.Add("PASS: live frames submitted="+scene.PresentedFrames);if(++step==1)scene.Bind();else{timer.Stop();scene.Close();}}catch(Exception ex){lines.Add("FAIL: "+ex.Message);timer.Stop();scene.Close();}};Application.Run(scene);}lines.Add(DesktopHost.IsWindow(surface)?"FAIL: wallpaper handle survived disposal":"PASS: original desktop restored by disposing only the farm surface");}catch(Exception e){lines.Add("FAIL: "+e);}File.WriteAllLines(Path.Combine(path,"desktop-verification.txt"),lines);Environment.ExitCode=lines.Any(x=>x.StartsWith("FAIL"))?1:0;}
 static void Render(string path){Directory.CreateDirectory(path);var farm=new Farm(Farm.UtcNow);farm.S.IntroSeen=true;farm.S.Lighting="白天";using(var form=new GameForm(farm,Path.Combine(path,"unused.json"),true)){using(var b=form.RenderSnapshot())b.Save(Path.Combine(path,"new-farm.png"));}
 var late=new Farm(Farm.UtcNow);late.S.Lighting="白天";late.S.Xp=Farm.Threshold(10);late.S.Land=2;late.S.Coins=1286;late.S.PetLove=35;late.S.IntroSeen=true;late.S.Guide=7;late.S.Plots.Clear();for(int i=0;i<36;i++){var crop=Farm.Crops[i%9];late.S.Plots.Add(new Plot{Crop=crop.Id,Planted=late.Now-crop.Seconds,Ready=late.Now+(i%4==0?60:-1),Watered=i%2==0});}foreach(string id in Farm.BuildingIds)late.S.Buildings[id]=1;late.S.Animals.Add(new Animal{Type="chicken"});late.S.Animals.Add(new Animal{Type="cow"});late.S.Animals.Add(new Animal{Type="sheep"});late.S.Animals.Add(new Animal{Type="bee"});late.S.Decorations.Add(new Decoration{Type="flowers",X=391,Y=185});late.S.Decorations.Add(new Decoration{Type="fountain",X=192,Y=177});using(var form=new GameForm(late,Path.Combine(path,"unused.json"),true)){using(var b=form.RenderSnapshot())b.Save(Path.Combine(path,"grown-farm.png"));foreach(string name in new[]{"inventory","workshop","orders","build","pet","journal","settings"})using(var b=form.RenderPanelSnapshot(name,""))b.Save(Path.Combine(path,name+".png"));using(var b=form.RenderPanelSnapshot("build","decor"))b.Save(Path.Combine(path,"decorations.png"));}using(var world=PixelArt.World(late,15,true,-1,null,Point.Empty)){world.MakeTransparent(Color.Magenta);world.Save(Path.Combine(path,"desktop-world.png"));}
 using(var landscape=new WallpaperForm(late,s=>{},()=>{},true))using(var frame=landscape.SceneSnapshot(960,540))frame.Save(Path.Combine(path,"wallpaper-grown.png"));using(var landscape=new WallpaperForm(farm,s=>{},()=>{},true))using(var frame=landscape.SceneSnapshot(960,540))frame.Save(Path.Combine(path,"wallpaper-new.png"));
 using(var b=new Bitmap(64,64)){using(var g=Graphics.FromImage(b)){g.Clear(PixelArt.C("547457"));g.ScaleTransform(2,2);PixelArt.Crop(g,5,8,"wheat",1,false,false,0);}using(var ms=new MemoryStream()){b.Save(ms,System.Drawing.Imaging.ImageFormat.Png);byte[] bytes=ms.ToArray();using(var writer=new BinaryWriter(File.Create(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","farm.ico")))){writer.Write((ushort)0);writer.Write((ushort)1);writer.Write((ushort)1);writer.Write((byte)64);writer.Write((byte)64);writer.Write((byte)0);writer.Write((byte)0);writer.Write((ushort)1);writer.Write((ushort)32);writer.Write(bytes.Length);writer.Write(22);writer.Write(bytes);}}}
 }
}
static class Tests {
 static int passed=0;static List<string> lines=new List<string>();
 static void Assert(bool ok,string name){if(!ok)throw new Exception("FAIL: "+name);passed++;lines.Add("PASS  "+name);}
 public static void Run(string path){Directory.CreateDirectory(path);try{double t=2000000000;var f=new Farm(()=>t);Assert(f.Level==1&&f.S.Plots.Count==12,"Fresh farm: 12 plots, level 1");int before=f.Count("wheat");f.Harvest(0);Assert(f.Count("wheat")==before+3&&f.S.Harvests==1,"Mature harvest deposits 3 wheat");int after=f.Count("wheat");f.Harvest(0);Assert(f.Count("wheat")==after,"Repeated harvest cannot duplicate crops");int coins=f.S.Coins;f.Plant(0,"wheat");Assert(f.S.Coins==coins-Farm.Crop("wheat").Cost&&f.S.Plots[0].Ready==t+Farm.Crop("wheat").Seconds,"Plant spends coins and starts real-time timer");f.Plant(0,"wheat");Assert(f.S.Coins==coins-Farm.Crop("wheat").Cost,"Occupied plot never charges twice");f.Water(0);Assert(f.S.Plots[0].Ready==t+Farm.Crop("wheat").Seconds*.8,"Water reduces remaining time 20 percent");double ready=f.S.Plots[0].Ready;f.Water(0);Assert(f.S.Plots[0].Ready==ready,"Water cannot be repeated");f.Harvest(0);Assert(f.S.Plots[0].Crop=="wheat","Cannot harvest immature crops");t+=Farm.Crop("wheat").Seconds*.8+1;f.Harvest(0);Assert(f.S.Plots[0].Crop=="","Harvest succeeds after elapsed real time");
 coins=f.S.Coins;f.Plant(0,"pumpkin");Assert(f.S.Coins==coins&&f.S.Plots[0].Crop=="","Locked crops cannot charge or plant");f.S.Coins=0;f.Plant(0,"wheat");Assert(f.S.Plots[0].Crop==""&&f.S.Coins==0,"Cannot plant with insufficient money");f.S.Coins=300;
 int wheat=f.Count("wheat");f.Craft("flour");Assert(f.Count("wheat")==wheat-2&&f.Queue("mill").Count==1,"Craft atomically spends ingredients");f.Craft("flour");int still=f.Count("wheat");f.Craft("flour");Assert(f.Count("wheat")==still&&f.Queue("mill").Count==2,"Queue capacity blocks additional ingredient spending");Assert(f.Queue("mill")[1].Ready-f.Queue("mill")[0].Ready==Farm.GetRecipe("flour").Seconds,"Jobs run sequentially");t+=Farm.GetRecipe("flour").Seconds+1;f.Tick();Assert(f.Count("flour")==1&&f.Queue("mill").Count==1,"First job deposits automatically");t+=Farm.GetRecipe("flour").Seconds;f.Tick();Assert(f.Count("flour")==2&&f.Queue("mill").Count==0,"Second job deposits automatically");f.Tick();Assert(f.Count("flour")==2,"Repeated tick never duplicates completed jobs");f.S.Xp=Farm.Threshold(2);f.S.Coins=2000;f.BuyBuilding("bakery");t=f.S.Construction["bakery"].Ready;f.Tick();Assert(f.Has("bakery"),"Level 2 bakery purchase");f.Craft("bread");Assert(f.Count("flour")==0&&f.Queue("bakery").Count==1,"Wheat to flour to bread production chain");t+=Farm.GetRecipe("bread").Seconds+1;f.Tick();Assert(f.Count("bread")==1,"Bread completes");coins=f.S.Coins;f.Sell("bread",99);Assert(f.Count("bread")==0&&f.S.Coins==coins+Farm.Price("bread"),"Sell clamps to owned quantity");coins=f.S.Coins;f.Sell("bread",1);Assert(f.S.Coins==coins,"Empty inventory cannot generate money");
 f.S.Inventory["wheat"]=100;var order=f.S.OrdersList[0];coins=f.S.Coins;f.Deliver(0);Assert(f.S.Orders==1&&f.S.Coins>=coins+order.Coins,"Order delivers and rewards");f.S.Inventory.Clear();int orders=f.S.Orders;coins=f.S.Coins;f.Deliver(0);Assert(f.S.Orders==orders&&f.S.Coins==coins,"Unfilled order never rewards");
 f.S.Coins=20000;f.S.Xp=Farm.Threshold(5);f.Expand();Assert(f.S.Land==1&&f.S.Plots.Count==24,"First expansion adds 12 plots");f.Expand();Assert(f.S.Land==2&&f.S.Plots.Count==36,"Second expansion adds 12 plots");coins=f.S.Coins;f.Expand();Assert(f.S.Plots.Count==36&&coins==f.S.Coins,"Level gate blocks early further expansion without charging");f.BuyBuilding("coop");t=f.S.Construction["coop"].Ready;f.Tick();Assert(f.S.Animals.Count==1,"Coop includes a chicken");f.S.Inventory["wheat"]=3;f.AnimalAction(0);Assert(f.Count("wheat")==0&&f.S.Animals[0].Fed,"Animal feeding spends correct food");f.AnimalAction(0);Assert(f.Count("egg")==0,"Animal produces only after timer");t=f.S.Animals[0].Ready+1;f.AnimalAction(0);Assert(f.Count("egg")==2&&!f.S.Animals[0].Fed,"Ready animal harvest is repeat-safe");f.AnimalAction(0);Assert(f.Count("egg")==2,"Animal cannot duplicate output");
 f.Pet();int love=f.S.PetLove;f.Pet();Assert(f.S.PetLove==love,"Pet cooldown prevents affection spam");t+=61;f.Pet();Assert(f.S.PetLove==love+2,"Pet cooldown expires correctly");coins=f.S.Coins;f.Daily();int giftCoins=f.S.Coins;f.Daily();Assert(f.S.Coins==giftCoins&&giftCoins>coins,"Daily gift claim is idempotent");f.CheckAchievements();int achievementCoins=f.S.Coins;f.CheckAchievements();Assert(f.S.Coins==achievementCoins,"Achievement rewards are idempotent");
 f.S.Coins=100;f.BuyDecoration("flowers",390,180);Assert(f.S.Decorations.Count==1&&f.S.Coins==75,"Decoration purchase persists coordinates and spends coins");f.S.Inventory["wheat"]=10;f.Craft("flour");string save=Path.Combine(path,"test-save.json");f.Save(save);f.Save(save);Assert(File.Exists(save+".bak"),"Atomic save creates a recoverable backup");var loaded=new Farm(()=>t+7200);loaded.Load(save);Assert(loaded.S.Plots.Count==36&&loaded.S.Decorations.Count==1,"Save/load preserves expansions and decorations");Assert(loaded.Queue("mill").Count==0&&loaded.Count("flour")>=1,"Offline production catches up on load");string saved=File.ReadAllText(save);File.WriteAllText(save,"{corrupt");var backup=new Farm(()=>t);backup.Load(save);Assert(backup.LoadNotice.Contains("备份")&&backup.S.Plots.Count==36,"Corrupt primary save recovers valid backup");File.WriteAllText(save,saved);var backward=new Farm(()=>t-500);backward.Load(save);Assert(backward.S.Coins>=0&&backward.Queue("mill").Count==1,"Backward clock does not complete future work or delete progress");
 var longRun=new Farm(()=>t);longRun.S.Xp=Farm.Threshold(10);longRun.S.Coins=5000;foreach(var id in Farm.BuildingIds)longRun.S.Buildings[id]=1;foreach(var c in Farm.Crops)longRun.Add(c.Id,100);foreach(var r in Farm.Recipes){foreach(var input in r.Inputs)longRun.Add(input.Key,10);longRun.Craft(r.Id);t+=7200;longRun.Tick();Assert(longRun.Count(r.Id)>=1,"End-to-end recipe: "+r.Name);}longRun.S.Inventory["bread"]=5;longRun.S.Inventory["milk"]=6;longRun.S.Inventory["jam"]=2;coins=longRun.S.Coins;longRun.Train();Assert(longRun.S.Coins==coins+700,"Train bulk delivery rewards and consumes goods");Farm.Validate(longRun.S);Assert(true,"Late-game state passes save validation");
 var rescue=new Farm(()=>t);rescue.S.Coins=0;rescue.S.Inventory.Clear();foreach(var plot in rescue.S.Plots)plot.Crop="";rescue.Tick();Assert(rescue.S.Coins==10,"Empty farm receives seed money to avoid economic deadlock");rescue.Tick();Assert(rescue.S.Coins==10,"Recovery gift cannot be repeatedly claimed");int queueCount=longRun.S.Queues.Count;longRun.Queue("unbuilt");Assert(longRun.S.Queues.Count==queueCount,"Reading a missing queue never mutates save data");var json=new System.Web.Script.Serialization.JavaScriptSerializer();string modelBefore=json.Serialize(longRun.S);using(var ui=new GameForm(longRun,Path.Combine(path,"unused-ui.json"),true)){foreach(string screen in new[]{"inventory","workshop","orders","build","pet","journal","settings"}){using(var bitmap=ui.RenderPanelSnapshot(screen,"")){Assert(bitmap.Width==1200&&bitmap.Height==800,"UI renders: "+screen);}}using(var bitmap=ui.RenderPanelSnapshot("build","decor")){Assert(bitmap.Width==1200,"Decoration screen renders");}}Assert(json.Serialize(longRun.S)==modelBefore,"Rendering every panel leaves player save unchanged");Farm.Validate(longRun.S);Assert(true,"UI inspection preserves save validity");V02Tests.Run(path,Assert);V03Tests.Run(path,Assert);V04Tests.Run(path,Assert);V05Tests.Run(path,Assert);V06Tests.Run(path,Assert);V07Tests.Run(Assert);V09Tests.Run(path,Assert);V010Tests.Run(path,Assert);V012Tests.Run(path,Assert);lines.Add("\nTOTAL: "+passed+" passed, 0 failed");File.WriteAllLines(Path.Combine(path,"test-results.txt"),lines,Encoding.UTF8);Environment.ExitCode=0;}catch(Exception e){lines.Add(e.ToString());File.WriteAllLines(Path.Combine(path,"test-results.txt"),lines,Encoding.UTF8);Environment.ExitCode=1;}}
}
}
