using System;
using System.Linq;
using System.IO;
using System.Drawing;
using System.Web.Script.Serialization;
namespace DesktopFarm {
public static class V012Tests {
 static Point OpenSpot(Farm f,WorldObject item){var all=FreeLayout.Objects(f,960,540);for(int y=280;y<=500;y+=10)for(int x=600;x<=950;x+=10){Point p=FreeLayout.Clamp(item,new Point(x,y),960,540);if(p==item.Foot||!FreeLayout.CanPlace(item,p,all))continue;Point old=item.Foot;item.Foot=p;var solid=item.Solid;item.Foot=old;if(WorldMap.Dry(f,solid))return p;}return Point.Empty;}
 static WorldObject TopAt(System.Collections.Generic.List<WorldObject> objects,Point p){return objects.OrderBy(o=>o.Kind=="path"?-1:o.Foot.Y).LastOrDefault(o=>o.Kind=="plot"?o.Solid.Contains(p):o.Bounds.Contains(p));}
 public static void Run(string path,Action<bool,string> check){var f=new Farm(()=>2000000000);f.S.Coins=100000;f.S.Xp=Farm.Threshold(20);f.S.DesktopLayout["path:0"]=new LayoutPoint{X=.5,Y=.7};string roads=new JavaScriptSerializer().Serialize(f.S.DesktopLayout);double ready=f.S.Plots[0].Ready;
 for(int stage=1;stage<=7;stage++){int coins=f.S.Coins,cost=f.ExpandCost;f.Expand();check(f.S.Plots.Count==Farm.PlotCounts[stage]&&f.S.Coins==coins-cost+(stage==1?50:0),"Expansion stage "+stage+" grants the advertised plot count and charges once");}int balance=f.S.Coins;f.Expand();check(f.S.Plots.Count==81&&f.S.Coins==balance,"81 is the hard limit; further expansion never charges");check(roads==new JavaScriptSerializer().Serialize(f.S.DesktopLayout)&&ready==f.S.Plots[0].Ready,"Expanding preserves roads and existing crop deadlines");var world=FreeLayout.Objects(f,960,540);var fields=world.Where(o=>o.Kind=="plot").ToArray();check(fields.Length==81,"All 81 fields remain on the wallpaper");check(fields.All(o=>!world.Any(r=>r.Kind=="path"&&r.Solid.IntersectsWith(o.Solid))),"Default field placements leave road tiles clear");Point first=fields[0].Foot;var road=world.First(o=>o.Id=="path:1");check(!FreeLayout.Move(f,"plot:0",road.Foot,960,540)&&FreeLayout.Objects(f,960,540).First(o=>o.Id=="plot:0").Foot==first,"Fields can move freely but cannot cover a road");check(FreeLayout.Move(f,"plot:0",new Point(760,330),960,540),"A field moves onto open meadow");
 using(var scene=new WallpaperForm(f,s=>{},()=>{},true)){var all=FreeLayout.Objects(f,960,540);var field=all.Where(o=>o.Kind=="plot").FirstOrDefault(o=>{var hit=new Point(o.Foot.X,o.Foot.Y-10);var top=TopAt(all,hit);return top!=null&&top.Id==o.Id&&!scene.ActorPositions.Any(a=>Math.Abs(a.X-hit.X)<22&&hit.Y>a.Y-30&&hit.Y<a.Y+10);});Point target=field==null?Point.Empty:OpenSpot(f,field);if(field!=null){Point hit=new Point(field.Foot.X,field.Foot.Y-10);scene.ClientInput("down",hit.X/960.0,hit.Y/540.0);scene.ClientInput("move",target.X/960.0,(target.Y-10)/540.0);scene.ClientInput("up",target.X/960.0,(target.Y-10)/540.0);}var dragged=field==null?null:FreeLayout.Objects(f,960,540).First(o=>o.Id==field.Id);check(target!=Point.Empty&&dragged!=null&&dragged.Foot==target,"A field can be dragged directly across the wallpaper");DesktopHud.Apply(f,scene,new DesktopHud.Command{action="plot",id="80"});check(f.S.Plots[80].Crop=="wheat","Last of 81 plots can be planted through the page action");int coins=f.S.Coins;DesktopHud.Apply(f,scene,new DesktopHud.Command{action="plot",id="81"});check(f.S.Coins==coins,"Out-of-range plot action cannot spend coins");}
 f.S.HotkeyMods=1;f.S.HotkeyKey=70;string file=Path.Combine(path,"fields-shortcut.json");f.Save(file);var restored=new Farm(()=>2000000000);restored.Load(file);check(restored.S.Plots.Count==81&&restored.S.HotkeyMods==1&&restored.S.HotkeyKey==70,"81 fields and a custom shortcut survive save/load");check(ShortcutKeys.Valid(0,119)&&ShortcutKeys.Valid(1,70)&&!ShortcutKeys.Valid(0,70)&&!ShortcutKeys.Valid(0,123),"Shortcut validation permits F8 / Alt+F and rejects bare typing or reserved F12");
 using(var form=new GameForm(f,Path.Combine(path,"unused-fields.json"),true)){using(var image=form.RenderPanelSnapshot("fields",""))image.Save(Path.Combine(path,"fields-v1.1-actions.png"));var activeHits=(System.Collections.Generic.List<Hit>)typeof(GameForm).GetField("hits",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(form);check(!activeHits.Any(h=>h.Bounds.Width==34&&h.Bounds.Height==34),"Fields page contains no individual land-tile controls");var seedHit=activeHits.LastOrDefault(h=>h.Bounds.Contains(new Point(760,240)));seedHit.Action();var sowHit=activeHits.LastOrDefault(h=>h.Bounds.Contains(new Point(530,547)));int carrotsBefore=f.Count("carrot");sowHit.Action();check(f.S.SelectedSeed=="carrot"&&f.S.Plots.Any(p=>p.Crop=="carrot"),"Seed card and plant action work directly from the fields page");var planted=f.S.Plots.First(p=>p.Crop=="carrot");planted.Ready=f.Now-1;var harvestHit=activeHits.LastOrDefault(h=>h.Bounds.Contains(new Point(280,547)));harvestHit.Action();check(f.Count("carrot")>=carrotsBefore+3,"Harvest action collects ready crops from the fields page");var buyer=new Farm(()=>2000000000);buyer.S.Xp=Farm.Threshold(2);buyer.S.Coins=10000;using(var buyUi=new GameForm(buyer,Path.Combine(path,"unused-land-buy.json"),true)){var buyHits=(System.Collections.Generic.List<Hit>)typeof(GameForm).GetField("hits",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(buyUi);buyUi.RenderPanelSnapshot("fields","").Dispose();buyHits=(System.Collections.Generic.List<Hit>)typeof(GameForm).GetField("hits",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(buyUi);buyHits.LastOrDefault(h=>h.Bounds.Contains(new Point(850,547))).Action();check(buyer.S.Land==1&&buyer.S.Plots.Count==24,"Land purchase action works directly from the fields page");}form.ChangeShortcut("1,71");check(f.S.HotkeyMods==1&&f.S.HotkeyKey==71,"Custom shortcut updates saved configuration");form.ChangeShortcut("0,65");check(f.S.HotkeyKey==71,"Invalid shortcuts do not overwrite the previous binding");form.ChangeShortcut("0,0");check(f.S.HotkeyKey==0,"Player can disable the global shortcut");}
 var old=new Farm(()=>2000000000).S;old.Version=2;old.Land=2;while(old.Plots.Count<36)old.Plots.Add(new Plot());int oldCoins=old.Coins;Farm.Validate(old);check(old.Version==4&&old.Plots.Count==36&&old.Coins==oldCoins,"Version 2 migration preserves owned land and coins");
 }
}
}
