using System;
using System.Linq;
using System.IO;
using System.Drawing;
using System.Web.Script.Serialization;
namespace DesktopFarm {
public static class V09Tests {
 static bool Diff(Bitmap a,Bitmap b){for(int y=0;y<a.Height;y++)for(int x=0;x<a.Width;x++)if(a.GetPixel(x,y)!=b.GetPixel(x,y))return true;return false;}
 public static void Run(string path,Action<bool,string> check){double time=2000000000;var f=new Farm(()=>time);f.S.Coins=100000;f.S.Xp=Farm.Threshold(20);
 int coins=f.S.Coins;f.BuyBuilding("coop");check(!f.Has("coop")&&f.S.Construction.ContainsKey("coop")&&f.S.Coins==coins-280,"Purchase starts timed construction and charges once");coins=f.S.Coins;f.BuyBuilding("coop");check(f.S.Coins==coins&&f.S.Construction.Count==1,"Repeated purchase cannot charge or duplicate construction");f.BuyBuilding("barn");coins=f.S.Coins;f.BuyBuilding("bakery");check(f.S.Construction.Count==2&&f.S.Coins==coins,"Two builders enforce concurrency without spending on rejection");
 time=f.S.Construction["coop"].Ready-1;f.Tick();check(!f.Has("coop")&&f.S.Animals.Count==0,"Animal is not awarded before its building completes");time++;f.Tick();check(f.Has("coop")&&f.S.Animals.Count==1,"Completion awards the building and animal");f.Tick();check(f.S.Animals.Count==1,"Repeated completion ticks do not duplicate animals");time=f.S.Construction["barn"].Ready+1;f.Tick();f.Craft("flour");coins=f.S.Coins;f.Upgrade("mill");check(!f.S.Construction.ContainsKey("mill")&&coins==f.S.Coins,"Pending production blocks upgrade before charging");check(f.Queue("mill").Count==1,"Flour is queued before construction starts");f.Upgrade("coop");check(f.S.Buildings["coop"]==1&&f.S.Construction["coop"].TargetLevel==2,"Upgrade keeps the old tier until its deadline");int wheat=f.Count("wheat"),queued=f.Queue("mill").Count;double queuedRemaining=f.ProductionRemaining(f.Queue("mill")[0].Ready);f.Craft("flour");check(f.Count("wheat")==wheat&&f.Queue("mill").Count==queued,"Any active construction blocks new production without consuming ingredients");double resume=f.S.ProductionPausedUntil;time+=30;f.Tick();check(Math.Abs(f.ProductionRemaining(f.Queue("mill")[0].Ready)-queuedRemaining)<.1,"Queued production progress stays paused during construction");time=resume+1;f.Tick();check(f.S.Construction.Count==0&&f.Queue("mill").Count==1,"Existing workshop job resumes after construction");time=f.Queue("mill")[0].Ready+1;f.Tick();check(f.Queue("mill").Count==0,"Paused production finishes after the remaining time");f.Upgrade("mill");f.Upgrade("coop");
 string saved=Path.Combine(path,"construction-save.json");f.Save(saved);var offline=new Farm(()=>time+86401);offline.Load(saved);check(offline.S.Construction.Count==0&&offline.S.Buildings["coop"]==3&&offline.S.Buildings["mill"]==2,"Construction and upgrades finish once after an offline interval");check(offline.S.Animals.Count==2,"Upgrading animal buildings never adds duplicate animals");var backwards=new Farm(()=>time-500);backwards.Load(saved);check(backwards.S.Construction.Count==2,"A backward clock cannot finish future construction");
 var old=new Farm(()=>time).S;old.Version=1;old.Xp=1245;old.Coins=304;old.Buildings.Remove("cabin");old.DesktopLayout["cabin"]=new LayoutPoint{X=.33,Y=.6};Farm.Validate(old);check(old.Version==4&&old.Xp>=Farm.Threshold(14)&&old.Xp<Farm.Threshold(15)&&old.Coins==304,"Legacy economy migration preserves farm level and coins");check(old.DesktopLayout["cabin"].X==.33&&old.Buildings["cabin"]==1,"Legacy layout and starter farmhouse are preserved");int xp=old.Xp;Farm.Validate(old);check(xp==old.Xp,"Economy migration is idempotent");
 var mapFarm=new Farm(()=>time);coins=mapFarm.S.Coins;WorldMap.Select(mapFarm,"river");check(mapFarm.S.Map=="meadow"&&mapFarm.S.Coins==coins,"Unaffordable map cannot change the world or charge");mapFarm.S.Coins=2500;WorldMap.Select(mapFarm,"river");check(mapFarm.S.Coins==0&&mapFarm.S.Map=="river"&&mapFarm.S.OwnedMaps.Contains("river"),"Exact-price river unlock works");WorldMap.Select(mapFarm,"meadow");WorldMap.Select(mapFarm,"river");check(mapFarm.S.Coins==0,"Owned maps switch without a second purchase");check(WorldMap.Water("river",WorldMap.RiverX(300),300)&&!WorldMap.Water("river",WorldMap.RiverX(180),180),"River water and bridge crossing match terrain collision");
 using(var scene=new WallpaperForm(mapFarm,s=>{},()=>{},true)){scene.ExternalHud=true;scene.PanTo(960,540);check(mapFarm.S.CameraX==960&&mapFarm.S.CameraY==540,"Camera reaches the far world edge");scene.PanTo(9999,-9999);check(mapFarm.S.CameraX==960&&mapFarm.S.CameraY==-540,"Camera clamps at world boundaries");scene.PanTo(0,0);string layoutBeforePan=new JavaScriptSerializer().Serialize(mapFarm.S.DesktopLayout);scene.Navigate("toggle");scene.ClientInput("down",.5,.5);scene.ClientInput("move",.2,.3);scene.ClientInput("up",.2,.3);check(mapFarm.S.CameraX==288&&mapFarm.S.CameraY==108,"Map dragging moves the viewport by the pointer distance");check(layoutBeforePan==new JavaScriptSerializer().Serialize(mapFarm.S.DesktopLayout),"Panning never rewrites object placements");scene.Navigate("toggle");scene.PanTo(800,0);check(FreeLayout.Move(mapFarm,"cabin",new Point(500,250),960,540),"Building can be placed beyond the original single screen");var house=FreeLayout.Objects(mapFarm,960,540).First(o=>o.Id=="cabin");check(house.Foot==new Point(500,250),"Moved building and hit target use the camera transform");string layout=new JavaScriptSerializer().Serialize(mapFarm.S.DesktopLayout);int river=WorldMap.RiverX(300)-mapFarm.S.CameraX;check(!FreeLayout.Move(mapFarm,"cabin",new Point(river,300),960,540)&&layout==new JavaScriptSerializer().Serialize(mapFarm.S.DesktopLayout),"River placement is rejected without changing layout");scene.Navigate("home");house=FreeLayout.Objects(mapFarm,960,540).First(o=>o.Id=="cabin");check(Math.Abs(house.Foot.X-480)<2&&Math.Abs(house.Foot.Y-270)<2,"Home navigation finds the moved farmhouse");}
 saved=Path.Combine(path,"world-save.json");mapFarm.Save(saved);var restored=new Farm(()=>time);restored.Load(saved);check(restored.S.Map=="river"&&restored.S.OwnedMaps.Contains("river")&&restored.S.DesktopLayout["cabin"].X==mapFarm.S.DesktopLayout["cabin"].X&&restored.S.CameraX==mapFarm.S.CameraX,"Map ownership, camera and off-screen placement survive restart");
 var economy=new Farm(()=>time);int profit=3*Farm.Price("wheat")-Farm.Crop("wheat").Cost;check(profit==3&&Farm.Crop("wheat").Seconds==300,"Wheat hourly profit is reduced from 390 to 36 per plot");int oldXp=economy.S.Xp;economy.S.Inventory["wheat"]=100;economy.S.Achievements.Add("rich");economy.Sell("wheat",100);check(economy.S.Xp==oldXp,"Selling goods does not farm experience points");check(Farm.Threshold(10)==3240,"Midgame progression needs the revised experience curve");foreach(var recipe in Farm.Recipes)check(recipe.Price>recipe.Inputs.Sum(p=>Farm.Price(p.Key)*p.Value),"Processing has a positive sale margin: "+recipe.Id);
 Render(path,check);
 }
 static void Render(string path,Action<bool,string> check){var f=new Farm(()=>2000000000);f.S.Lighting="白天";f.S.Xp=Farm.Threshold(20);foreach(var id in Farm.BuildingIds)f.S.Buildings[id]=1;
 using(var sheet=new Bitmap(1400,580))using(var g=Graphics.FromImage(sheet)){g.Clear(PixelArt.C("eee8d1"));for(int col=0;col<Farm.BuildingIds.Length;col++){string id=Farm.BuildingIds[col];Bitmap previous=null;for(int row=0;row<4;row++){f.S.Buildings[id]=Math.Min(3,row+1);if(row==3)f.S.Construction[id]=new Construction{FromLevel=1,TargetLevel=2,Started=f.Now-100,Ready=f.Now+500};using(var sprite=new Bitmap(128,128))using(var sg=Graphics.FromImage(sprite)){sg.Clear(Color.Transparent);BuildingArt.ForFarm(sg,f,64,112,id,1);if(previous!=null&&row<3)check(Diff(previous,sprite),"Visible upgrade detail: "+id+" tier "+(row+1));if(previous!=null)previous.Dispose();previous=(Bitmap)sprite.Clone();g.InterpolationMode=System.Drawing.Drawing2D.InterpolationMode.NearestNeighbor;g.DrawImage(sprite,col*140,row*140,128,128);using(var font=new Font("Segoe UI",8))g.DrawString(id+" / "+(row==3?"build":"Lv."+(row+1)),font,Brushes.DarkOliveGreen,col*140+2,row*140+126);}f.S.Construction.Remove(id);}if(previous!=null)previous.Dispose();}sheet.Save(Path.Combine(path,"building-tiers.png"));}
 foreach(string id in WorldMap.Ids){f.S.Map=id;f.S.CameraX=id=="river"?320:id=="lake"?-850:0;f.S.CameraY=id=="lake"?-200:0;using(var scene=new WallpaperForm(f,s=>{},()=>{},true)){scene.ExternalHud=true;using(var b=scene.SceneSnapshot(960,540))b.Save(Path.Combine(path,"world-"+id+".png"));}}
 }
}
}
