using System;
using System.Linq;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Windows.Forms;
using System.IO;

namespace DesktopFarm {
public class Wanderer {
 public string Type;public int AnimalIndex=-1;public double X,Y,TargetX,TargetY,Rest,WalkTime;public int Direction=1;public double Speed=15;
 public Wanderer(string type,int index,Point home){Type=type;AnimalIndex=index;X=TargetX=home.X;Y=TargetY=home.Y;Speed=index<0?18:type=="chicken"?13:type=="bee"?23:8;}
 public static bool Blocked(double x,double y,IList<Rectangle> blocks){return blocks.Any(b=>b.Contains((int)x,(int)y));}
 public bool Clear(double x,double y,IList<Rectangle> blocks){double d=Math.Sqrt((x-X)*(x-X)+(y-Y)*(y-Y));for(double t=4;t<=d;t+=4)if(Blocked(X+(x-X)*t/d,Y+(y-Y)*t/d,blocks))return false;return !Blocked(x,y,blocks);}
 public void Step(double dt,Rectangle area,Random random,IList<Rectangle> blocks){dt=Math.Min(.5,Math.Max(0,dt));if(Blocked(X,Y,blocks)){for(int r=4;r<100;r+=4)for(int a=0;a<16;a++){double x=X+Math.Cos(a*Math.PI/8)*r,y=Y+Math.Sin(a*Math.PI/8)*r;if(area.Contains((int)x,(int)y)&&!Blocked(x,y,blocks)){X=TargetX=x;Y=TargetY=y;Rest=0;return;}}}
 if(Rest>0){Rest-=dt;return;}double dx=TargetX-X,dy=TargetY-Y,dist=Math.Sqrt(dx*dx+dy*dy);if(dist<2){Choose(area,random,blocks);Rest=.4+random.NextDouble()*2;return;}double step=Math.Min(dist,Speed*dt),nx=X+dx/dist*step,ny=Y+dy/dist*step;if(Blocked(nx,ny,blocks)){Choose(area,random,blocks);Rest=.1;return;}X=Math.Max(area.Left,Math.Min(area.Right-1,nx));Y=Math.Max(area.Top,Math.Min(area.Bottom-1,ny));if(Math.Abs(dx)>.3)Direction=dx>0?1:-1;WalkTime+=dt;}
 public void Choose(Rectangle area,Random random,IList<Rectangle> blocks){for(int tries=0;tries<80;tries++){double angle=random.NextDouble()*Math.PI*2,d=tries<50?35+random.NextDouble()*150:8+random.NextDouble()*30;int x=(int)Math.Max(area.Left,Math.Min(area.Right-1,X+Math.Cos(angle)*d)),y=(int)Math.Max(area.Top,Math.Min(area.Bottom-1,Y+Math.Sin(angle)*d));if(Clear(x,y,blocks)){TargetX=x;TargetY=y;return;}}TargetX=X;TargetY=Y;}
 public void MoveTo(Point p,Rectangle area){X=TargetX=Math.Max(area.Left,Math.Min(area.Right-1,p.X));Y=TargetY=Math.Max(area.Top,Math.Min(area.Bottom-1,p.Y));Rest=3;}
}
public class WallpaperForm:Form {
 readonly Farm farm;readonly Action<string> openPanel;readonly Action changed;readonly bool preview;readonly Timer ticker=new Timer(),inputTimer=new Timer();readonly Random random=new Random();readonly List<Wanderer> actors=new List<Wanderer>();
 readonly Font small=new Font("Microsoft YaHei UI",12,FontStyle.Regular,GraphicsUnit.Pixel);
 DateTime last=DateTime.Now;double time,noteUntil,lastBind;bool wasDown,dragging,closing,armed;Wanderer dragged;WorldObject moving;Point pressedAt,offset,pointer;string note="",pending="",selectedId="";int logicalWidth=960,logicalHeight=540;Bitmap meadow;bool meadowNight;List<WorldObject> objects=new List<WorldObject>();
 public bool PanMode;bool panning;Point panStart,cameraStart;string meadowMap="";
 internal PointF[] ActorPositions {get{return actors.Select(a=>new PointF((float)a.X,(float)a.Y)).ToArray();}}
 public bool TraceInput;public string HostDetail="",RenderError="";public int PresentedFrames;public bool EditMode,ExternalHud;
 public string CurrentNote {get{return time<noteUntil?L.T(note):"";}}
 public string PendingName {get{return pending==""?"":L.T(Farm.DecorName(pending));}}
 public void ChooseDecoration(string type){PanMode=false;pending=type;EditMode=true;Cancel();}
 public bool IsAttached {get{return !preview&&IsHandleCreated&&(DesktopHost.ClassName(DesktopHost.GetParent(Handle))=="WorkerW"||DesktopHost.ClassName(DesktopHost.GetParent(Handle))=="Progman");}}
 public WallpaperForm(Farm f,Action<string> open,Action onChanged,bool asPreview){farm=f;openPanel=open;changed=onChanged;preview=asPreview;EditMode=preview;Text="Mosslight — Desktop Landscape";DoubleBuffered=true;ShowInTaskbar=preview;FormBorderStyle=preview?FormBorderStyle.Sizable:FormBorderStyle.None;StartPosition=preview?FormStartPosition.CenterScreen:FormStartPosition.Manual;BackColor=PixelArt.C("8fad69");var screen=GetScreen();if(preview){ClientSize=new Size(Math.Min(1440,screen.WorkingArea.Width-100),Math.Min(810,screen.WorkingArea.Height-100));MinimumSize=new Size(800,540);}else Bounds=screen.Bounds;
  ticker.Interval=80;ticker.Tick+=(s,e)=>TickScene();Shown+=(s,e)=>{if(!preview&&!IsAttached&&!Bind())Hide();};ticker.Start();if(!preview){inputTimer.Interval=50;inputTimer.Tick+=(s,e)=>{inputTimer.Interval=(DesktopHost.GetAsyncKeyState(0x12)&0x8000)!=0?16:80;PollPointer();};inputTimer.Start();}KeyPreview=true;
 }
 protected override bool ShowWithoutActivation {get{return !preview;}}
 protected override CreateParams CreateParams {get{var p=base.CreateParams;if(!preview)p.ExStyle|=0x08000000|0x00000080;return p;}}
 Screen GetScreen(){var s=Screen.AllScreens;return s[Math.Max(0,Math.Min(s.Length-1,farm.S.Monitor))];}
 public bool Bind(){Bounds=GetScreen().Bounds;bool result=DesktopHost.Attach(this,GetScreen().Bounds,out HostDetail);lastBind=time;if(result){SetLayout();Present();}return result&&RenderError=="";}
 public void Rebind(){if(!preview&&!Bind())Hide();}
 public void Announce(string text){note=text;noteUntil=time+5;Invalidate();}
 public void CallAnimals(){SetLayout();var cabin=objects.FirstOrDefault(x=>x.Id=="cabin");Point home=cabin==null?new Point(logicalWidth/2,logicalHeight/2):new Point(cabin.Foot.X+55,cabin.Foot.Y+22);foreach(var a in actors){a.TargetX=home.X+random.Next(-14,22);a.TargetY=home.Y+random.Next(-10,20);a.Rest=0;}Announce("小伙伴们正在慢慢回家。");}
 Rectangle RoamArea {get{return new Rectangle(-938-farm.S.CameraX,-470-farm.S.CameraY,2836,1480);}}
 void SetLayout(){int pixel=Math.Max(1,Math.Min(ClientSize.Width/960,ClientSize.Height/540));logicalWidth=preview?960:Math.Max(640,ClientSize.Width/pixel);logicalHeight=preview?Math.Max(540,ClientSize.Height*960/Math.Max(1,ClientSize.Width)):Math.Max(340,ClientSize.Height/pixel);objects=FreeLayout.Objects(farm,logicalWidth,logicalHeight);}
 void SyncActors(){if(actors.Count==0){var cabin=objects.FirstOrDefault(x=>x.Id=="cabin");Point home=cabin==null?new Point(logicalWidth/2,logicalHeight/2):new Point(cabin.Foot.X+70,cabin.Foot.Y+35);actors.Add(new Wanderer(farm.S.Pet,-1,home));}actors[0].Type=farm.S.Pet;for(int i=0;i<farm.S.Animals.Count;i++){int index=i;if(!actors.Any(a=>a.AnimalIndex==index))actors.Add(new Wanderer(farm.S.Animals[i].Type,i,new Point(logicalWidth/2+50+i*24,logicalHeight-90)));}foreach(var a in actors){a.X=Math.Max(RoamArea.Left,Math.Min(RoamArea.Right-1,a.X));a.Y=Math.Max(RoamArea.Top,Math.Min(RoamArea.Bottom-1,a.Y));}}
 List<Rectangle> Obstacles(){var blocks=objects.Where(o=>!o.Solid.IsEmpty).Select(o=>o.Solid).ToList();for(int y=-470;y<1040;y+=20)for(int x=-940;x<1900;x+=20)if(WorldMap.Water(farm.S.Map,x,y))blocks.Add(new Rectangle(x-farm.S.CameraX,y-farm.S.CameraY,20,20));return blocks;}
 void TickScene(){if(closing)return;double dt=(DateTime.Now-last).TotalSeconds;last=DateTime.Now;time+=Math.Min(1,dt);SetLayout();if(armed&&dragging&&moving!=null&&!PanMode){int dx=pointer.X<22?-12:pointer.X>logicalWidth-22?12:0,dy=pointer.Y<65?-8:pointer.Y>logicalHeight-66?8:0;if(dx!=0||dy!=0)PanTo(farm.S.CameraX+dx,farm.S.CameraY+dy);}SyncActors();var blocks=Obstacles();foreach(var a in actors)if(a!=dragged)a.Step(dt,RoamArea,random,blocks);if(!preview){if(time-lastBind>5){lastBind=time;if(!IsAttached)Bind();}bool storm=LandscapeArt.Weather(farm)=="雨天"||LandscapeArt.Weather(farm)=="雪天";ticker.Interval=farm.S.Quiet?(storm?90:120):DesktopHost.DesktopForeground?(storm?33:45):(storm?90:150);Present();}else Invalidate();}
 Point Logical(Point p){return new Point((int)(p.X*logicalWidth/(double)Math.Max(1,ClientSize.Width)),(int)(p.Y*logicalHeight/(double)Math.Max(1,ClientSize.Height)));}
 static bool ActorAt(Wanderer a,Point p){return Math.Abs(a.X-p.X)<22&&p.Y>a.Y-30&&p.Y<a.Y+10;}
 WorldObject ObjectAt(Point p){return objects.OrderBy(o=>o.Kind=="path"?-1:o.Foot.Y).LastOrDefault(o=>o.Kind=="plot"?o.Solid.Contains(p):o.Bounds.Contains(p));}
 void PollPointer(){Point screen=Cursor.Position;pointer=Logical(PointToClient(screen));bool alt=(DesktopHost.GetAsyncKeyState(0x12)&0x8000)!=0,down=(DesktopHost.GetAsyncKeyState(1)&0x8000)!=0,usable=DesktopHost.DesktopUnderPointer(screen,Handle)&&ClientRectangle.Contains(PointToClient(screen));if(alt&&usable&&down&&!wasDown){Begin(pointer);armed=true;}if(down&&armed&&alt)Drag(pointer);if(!down&&wasDown){if(armed&&alt&&usable)End(pointer);else Cancel();armed=false;}wasDown=down;}
 static double Distance(Point a,Point b){return Math.Sqrt(Math.Pow(a.X-b.X,2)+Math.Pow(a.Y-b.Y,2));}
 void Begin(Point p){panning=PanMode;if(panning){panStart=p;cameraStart=new Point(farm.S.CameraX,farm.S.CameraY);moving=null;dragged=null;return;}pressedAt=p;dragging=false;moving=null;dragged=null;if((!ExternalHud&&(p.Y<59||p.Y>logicalHeight-62))||pending!="")return;dragged=actors.LastOrDefault(a=>ActorAt(a,p));if(dragged==null){moving=ObjectAt(p);if(moving!=null){offset=new Point(moving.Foot.X-p.X,moving.Foot.Y-p.Y);selectedId=moving.Id;}else{panning=true;panStart=p;cameraStart=new Point(farm.S.CameraX,farm.S.CameraY);}}}
 Point DropAt(Point p){return FreeLayout.Clamp(moving,new Point(p.X+offset.X,p.Y+offset.Y),logicalWidth,logicalHeight);}
 void Drag(Point p){if(panning){PanTo(cameraStart.X+panStart.X-p.X,cameraStart.Y+panStart.Y-p.Y);return;}if(Distance(p,pressedAt)>4)dragging=true;if(dragging&&dragged!=null)dragged.MoveTo(p,RoamArea);pointer=p;Invalidate();}
 void Cancel(){panning=false;dragged=null;moving=null;dragging=false;}
 void End(Point p){if(panning){Drag(p);panning=false;changed();return;}if((moving!=null||dragged!=null)&&Distance(p,pressedAt)>4)Drag(p);if(dragged!=null){if(!dragging){Announce(dragged.AnimalIndex<0?farm.Pet():farm.AnimalAction(dragged.AnimalIndex));changed();}Cancel();return;}if(moving!=null&&dragging){bool ok=FreeLayout.Move(farm,moving.Id,DropAt(p),logicalWidth,logicalHeight);Announce(ok?"位置已保存，动物会按新布局散步。":"这里与其他物品重叠，请换一个位置。");if(ok)changed();Cancel();return;}var clicked=moving;Cancel();if(!ExternalHud&&p.Y>=14&&p.Y<=49){if(p.X>=logicalWidth-170){openPanel("settings");return;}if(p.X>=logicalWidth-328){EditMode=!EditMode;pending="";Announce(EditMode?"布置模式：拖动建筑、田地、树木和装饰。":"布置完成，位置已保存。");return;}if(p.X>=logicalWidth-486){openPanel("");return;}}
  if(!ExternalHud&&EditMode&&p.Y>=logicalHeight-60&&p.Y<logicalHeight-30){string[] types={"path","flowers","fence","lamp","bench","tree","fountain"};int start=(logicalWidth-7*80)/2,index=(p.X-start)/80;if(p.X>=start&&index>=0&&index<types.Length){pending=types[index];Announce("点击空地放置；Esc 取消，放下时才扣金币。");}return;}
  if(pending!=""&&p.Y>65&&p.Y<logicalHeight-65){string type=pending;var candidate=new WorldObject{Kind=type=="path"?"path":"decor",Type=type,Foot=p};p=FreeLayout.Clamp(candidate,p,logicalWidth,logicalHeight);candidate.Foot=p;if(!WorldMap.Dry(farm,candidate.Bounds)||!FreeLayout.CanPlace(candidate,p,objects)){Announce("这里无法放置，请选择空草地。");return;}int old=farm.S.Decorations.Count;Announce(farm.BuyDecoration(type,390,185));if(farm.S.Decorations.Count>old){var d=farm.S.Decorations.Last();var item=new WorldObject{Id="decor:"+d.Key,Kind=type=="path"?"path":"decor",Type=type,Foot=p};Point pos=FreeLayout.Clamp(item,p,logicalWidth,logicalHeight);farm.S.DesktopLayout[item.Id]=new LayoutPoint{X=(pos.X+farm.S.CameraX)/(double)logicalWidth,Y=(pos.Y+farm.S.CameraY)/(double)logicalHeight};changed();}return;}
  if(clicked==null)return;selectedId=clicked.Id;if(EditMode){Announce(clicked.Label+" · 拖动即可移动");return;}if(clicked.Kind=="plot"){var crop=farm.S.Plots[clicked.Index];Announce(crop.Crop==""?farm.Plant(clicked.Index,farm.S.SelectedSeed):crop.Ready<=farm.Now?farm.Harvest(clicked.Index):farm.Water(clicked.Index));changed();}else if(clicked.Id=="cabin")openPanel("journal");else if(clicked.Id=="coop"||clicked.Id=="barn")openPanel(clicked.Id);else if(clicked.Kind=="building"||clicked.Kind=="mill"||clicked.Type=="bakery")openPanel("workshop");}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);pointer=Logical(e.Location);if(preview&&(e.Button&MouseButtons.Left)!=0)Drag(pointer);}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(preview&&e.Button==MouseButtons.Left)Begin(Logical(e.Location));}
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);if(preview&&e.Button==MouseButtons.Left)End(Logical(e.Location));if(preview&&e.Button==MouseButtons.Right){pending="";Cancel();}}
 protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);if(e.KeyCode==Keys.Escape){pending="";Cancel();}if(e.KeyCode==Keys.Space){EditMode=!EditMode;pending="";}}
 void Label(Graphics g,string text,Rectangle r){using(var b=new SolidBrush(PixelArt.C("f7f1dc")))using(var sf=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center,Trimming=StringTrimming.EllipsisCharacter})g.DrawString(L.T(text),small,b,r,sf);}
 void DrawActor(Graphics g,Wanderer a){if(a.AnimalIndex<0)PixelArt.Cat(g,(int)a.X,(int)a.Y,a.WalkTime,a.Type=="dog",a.Rest>3,a.Direction,farm.Now-farm.S.LastPet<4);else if(a.Type=="bee"){for(int i=0;i<3;i++){int x=(int)a.X+(int)(Math.Sin(time*3+i*2)*7),y=(int)a.Y+(int)(Math.Cos(time*2+i)*5);PixelArt.R(g,"ebeed3",x,y-3,3,2);PixelArt.R(g,"e5bb63",x,y,5,3);PixelArt.R(g,"675443",x+2,y,1,3);}}else{var s=g.Save();g.TranslateTransform((int)a.X,(int)a.Y);g.ScaleTransform(a.Direction,1);PixelArt.Animal(g,0,0,a.Type,a.WalkTime,a.Rest>2);g.Restore(s);}if(a.AnimalIndex>=0){var animal=farm.S.Animals[a.AnimalIndex];if(animal.Fed&&animal.Ready<=farm.Now){PixelArt.R(g,"f6ebc3",(int)a.X-4,(int)a.Y-34,10,8);PixelArt.R(g,"719369",(int)a.X,(int)a.Y-32,2,4);}}}
 Bitmap DrawScene(bool includeActors,bool ui){if(meadow==null||meadowNight!=farm.IsNight||meadowMap!=farm.S.Map){if(meadow!=null)meadow.Dispose();meadow=WorldMap.Backdrop(farm);meadowNight=farm.IsNight;meadowMap=farm.S.Map;}var b=new Bitmap(logicalWidth,logicalHeight);using(var g=Graphics.FromImage(b)){g.DrawImage(meadow,new Rectangle(0,0,logicalWidth,logicalHeight),new Rectangle(farm.S.CameraX+960,farm.S.CameraY+540,960,540),GraphicsUnit.Pixel);g.SmoothingMode=SmoothingMode.None;LandscapeArt.Back(g,farm,time,logicalWidth,logicalHeight,objects);var visible=objects.Where(o=>!(ui&&dragging&&moving!=null&&o.Id==moving.Id)).Select(o=>new KeyValuePair<double,Action>(o.Kind=="path"?-1:o.Foot.Y,()=>o.Draw(g,farm,time,false))).ToList();if(includeActors)foreach(var a in actors){var actor=a;visible.Add(new KeyValuePair<double,Action>(actor.Y,()=>DrawActor(g,actor)));}foreach(var action in visible.OrderBy(x=>x.Key))action.Value();
  if(ui&&moving!=null&&dragging){Point old=moving.Foot;moving.Foot=DropAt(pointer);moving.Draw(g,farm,time,false);moving.Foot=old;}
  if(ui&&pending!=""){var ghost=new WorldObject{Kind=pending=="path"?"path":"decor",Type=pending,Foot=pointer};ghost.Draw(g,farm,time,false);}
  LandscapeArt.Fore(g,farm,time,logicalWidth,logicalHeight,objects);
  if(ui&&!ExternalHud){g.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;using(var brush=new SolidBrush(Color.FromArgb(235,61,82,65))){for(int i=0;i<3;i++)g.FillRectangle(brush,logicalWidth-486+i*158,14,150,35);g.FillRectangle(brush,12,logicalHeight-29,logicalWidth-24,23);if(EditMode)g.FillRectangle(brush,(logicalWidth-560)/2,logicalHeight-61,560,30);}
   Label(g,"打开农场",new Rectangle(logicalWidth-486,14,150,35));Label(g,EditMode?"完成布置":"布置桌面",new Rectangle(logicalWidth-328,14,150,35));Label(g,"设置 / 语言",new Rectangle(logicalWidth-170,14,150,35));
   if(EditMode){string[] types={"path","flowers","fence","lamp","bench","tree","fountain"};for(int i=0;i<7;i++)Label(g,Farm.DecorName(types[i])+" "+Farm.DecorCost(types[i])+" G",new Rectangle((logicalWidth-560)/2+i*80,logicalHeight-61,80,30));}
   Label(g,preview?(EditMode?"直接拖动物品布置 · 空格切换游玩 · Esc 取消":"直接点击田地或动物 · 拖动任何物品 · 空格布置"):(EditMode?"Alt + 拖动任何物品 · Alt + 点击下方商店 · 完成布置后可收菜":"Alt + 点击收菜 · Alt + 拖动任何物品 · "+(farm.S.HotkeyKey==0?"从设置打开农场":ShortcutKeys.Label(farm.S.HotkeyMods,farm.S.HotkeyKey)+" 打开农场")),new Rectangle(20,logicalHeight-28,logicalWidth-40,22));
   if(time<noteUntil){using(var br=new SolidBrush(Color.FromArgb(240,60,80,63)))g.FillRectangle(br,logicalWidth/2-250,logicalHeight-103,500,32);Label(g,note,new Rectangle(logicalWidth/2-243,logicalHeight-103,486,32));}
  }
 }return b;}
 public void PanTo(int x,int y){int nx=Math.Max(-960,Math.Min(960,x)),ny=Math.Max(-540,Math.Min(540,y)),dx=nx-farm.S.CameraX,dy=ny-farm.S.CameraY;farm.S.CameraX=nx;farm.S.CameraY=ny;foreach(var a in actors){a.X-=dx;a.TargetX-=dx;a.Y-=dy;a.TargetY-=dy;}objects=FreeLayout.Objects(farm,logicalWidth,logicalHeight);}
 public void Navigate(string id){Cancel();if(id=="toggle"){PanMode=!PanMode;pending="";}else if(id=="home"){var home=FreeLayout.Objects(farm,960,540).First(o=>o.Id=="cabin");PanTo(home.Foot.X+farm.S.CameraX-480,home.Foot.Y+farm.S.CameraY-270);}else PanTo(farm.S.CameraX+(id=="left"?-240:id=="right"?240:0),farm.S.CameraY+(id=="up"?-135:id=="down"?135:0));changed();}
 public bool NativeHit(double x,double y){return x>=0&&x<=1&&y>=0&&y<=1;}
 public void ClientInput(string phase,double x,double y){pointer=new Point((int)(x*960),(int)(y*540));logicalWidth=960;logicalHeight=540;objects=FreeLayout.Objects(farm,960,540);if(phase=="down"){Begin(pointer);armed=true;}if(phase=="move"&&armed)Drag(pointer);if(phase=="up"&&armed){End(pointer);armed=false;}if(phase=="cancel"){pending="";PanMode=false;Cancel();armed=false;}if(phase=="toggle"){PanMode=false;Cancel();EditMode=!EditMode;pending="";}if(TraceInput&&phase!="move")RuntimeLog.Write("Farm input "+phase+" at "+x.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+","+y.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+" object="+(moving==null?"none":moving.Id)+" armed="+armed+" note="+note);}
 public Bitmap SceneSnapshot(int width,int height,bool advance=false){if(advance)TickScene();int oldW=logicalWidth,oldH=logicalHeight;logicalWidth=width;logicalHeight=height;objects=FreeLayout.Objects(farm,width,height);SyncActors();var b=DrawScene(true,true);logicalWidth=oldW;logicalHeight=oldH;objects=FreeLayout.Objects(farm,oldW,oldH);return b;}
 public Bitmap ExportWallpaper(){SetLayout();using(var scene=DrawScene(false,false)){var size=GetScreen().Bounds.Size;var b=new Bitmap(size.Width,size.Height);using(var g=Graphics.FromImage(b)){g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(scene,new Rectangle(Point.Empty,size));}return b;}}
 void Present(){if(preview||!IsAttached)return;try{using(var scene=DrawScene(true,true))using(var full=new Bitmap(ClientSize.Width,ClientSize.Height,System.Drawing.Imaging.PixelFormat.Format32bppPArgb)){using(var g=Graphics.FromImage(full)){g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(scene,ClientRectangle);}DesktopHost.Present(this,full,GetScreen().Bounds);PresentedFrames++;RenderError="";}}catch(Exception e){RenderError=e.Message;}}
 protected override void OnPaint(PaintEventArgs e){if(!preview)return;base.OnPaint(e);SetLayout();SyncActors();using(var b=DrawScene(true,true)){e.Graphics.InterpolationMode=InterpolationMode.NearestNeighbor;e.Graphics.PixelOffsetMode=PixelOffsetMode.Half;e.Graphics.DrawImage(b,ClientRectangle);}}
 protected override void Dispose(bool disposing){if(disposing&&!closing){closing=true;ticker.Stop();ticker.Dispose();inputTimer.Stop();inputTimer.Dispose();if(!preview&&IsHandleCreated)DesktopHost.Detach(this);small.Dispose();if(meadow!=null)meadow.Dispose();}base.Dispose(disposing);}
}
}
