(() => {
 const native=globalThis.webkit?.messageHandlers?.farm;
 const post=(type,data)=>native?.postMessage({type,data});
 let saved=globalThis.initialSave;
 try{if(!native){const text=localStorage.getItem('mosslight-mac-v1');if(text)saved=JSON.parse(text);}globalThis.game=new MossFarm(saved);}catch(e){document.addEventListener('DOMContentLoaded',()=>{document.body.textContent='存档读取失败，原文件已保留。 / Save could not be read. Your original file is preserved.';});throw e;}
 const game=globalThis.game;game.startup=!!globalThis.initialStartup;
 function save(){game.tick();if(native)post('save',game.s);else localStorage.setItem('mosslight-mac-v1',JSON.stringify(game.s));}
 globalThis.nativeStartupResult=(enabled,error)=>{game.startup=enabled;if(error)game.say('登录启动：'+error,'Login startup: '+error);};
 globalThis.nativeSaveResult=error=>{if(error)game.say('保存失败：'+error,'Save failed: '+error);};
 globalThis.saveFarm=save;
 let actors=[],gesture=null,lastNight=null;const images={};
 function image(id){if(!images[id]){const i=new Image();i.src='sprites/'+id+'.png';images[id]=i;}return images[id];}
 const bounds=o=>o.kind==='plot'?[o.x-11,o.y-36,24,38]:o.kind==='pond'?[o.x-54,o.y-28,108,65]:o.kind==='mill'?[o.x-48,o.y-108,96,115]:o.kind==='cabin'?[o.x-46,o.y-82,92,94]:o.kind==='building'?[o.x-32,o.y-70,64,88]:o.type==='tree'||o.kind==='pine'?[o.x-32,o.y-74,64,82]:o.kind==='path'?[o.x-12,o.y-12,24,24]:[o.x-18,o.y-38,36,46];
 function objects(){const a=[],add=(id,kind,type,x,y,index=-1)=>{const p=game.s.DesktopLayout[id];a.push({id,kind,type,index,x:p?p.X*960:180+x,y:p?p.Y*540:210+y});};add('cabin','cabin','home',129,184);add('mill','mill','mill',424,184);add('pond','pond','pond',501,241);
 const poses={bakery:[82,270],coop:[169,270],barn:[421,275],dairy:[284,105],loom:[226,105],sugarhouse:[342,105],preserves:[499,164],station:[90,80]};for(const [id,[x,y]]of Object.entries(poses))if(game.s.Buildings[id])add(id,id==='bakery'?'cabin':'building',id,x,y);
 game.s.Plots.forEach((p,i)=>add('plot:'+i,'plot','plot',235+i%6*24,161+Math.floor(i/6)*23,i));[[47,185],[552,173],[201,145],[40,273],[569,290]].forEach(([x,y],i)=>add('tree:'+i,'tree','tree',x,y));for(let i=0;i<6;i++)add('pine:'+i,'pine','pine',i<3?28+i*25:458+(i-3)*25,122+i%3*4);for(let i=0;i<10;i++)add('path:'+i,'path','path',178+i*24,205);add('lamp:0','decor','lamp',197,220);add('bench:0','decor','bench',558,230);game.s.Decorations.forEach((d,i)=>add('decor:'+d.Key,d.Type==='path'?'path':'decor',d.Type,d.X,d.Y,i));return a;}
 function inside(x,y,b){return x>=b[0]&&x<=b[0]+b[2]&&y>=b[1]&&y<=b[1]+b[3]}
 function solid(o){if(['path','decor'].includes(o.kind)&&o.type!=='tree')return null;const [x,y,w,h]=bounds(o);return o.kind==='plot'?[o.x-11,o.y-20,22,20]:o.kind==='pond'?[x+6,y+5,w-12,h-15]:[x+8,o.y-20,w-16,24];}
 function overlaps(a,b){return a&&b&&a[0]<b[0]+b[2]&&a[0]+a[2]>b[0]&&a[1]<b[1]+b[3]&&a[1]+a[3]>b[1]}
 function input(d){const x=d.x*960,y=d.y*540;if(d.phase==='cancel'){gesture=null;game.act('cancel');save();return;}if(d.phase==='down'){const object=objects().sort((a,b)=>b.y-a.y).find(o=>inside(x,y,bounds(o))),actor=actors.find(a=>Math.abs(a.x-x)<20&&Math.abs(a.y-y)<24);gesture={object,actor,x,y,dx:object?x-object.x:0,dy:object?y-object.y:0,moved:false};}
 if(d.phase==='move'&&gesture){if(Math.hypot(x-gesture.x,y-gesture.y)>5)gesture.moved=true;gesture.at={x,y};}
 if(d.phase==='up'&&gesture){const g=gesture;gesture=null;if(game.pending&&!g.moved){if(game.s.Decorations.length>=24)game.say('装饰最多 24 件。','Decoration limit: 24.');else{const cost=game.decorCost(game.pending),o={kind:game.pending==='path'?'path':'decor',type:game.pending,x,y};if(game.s.Coins>=cost&&!objects().some(other=>overlaps(solid(o),solid(other)))){const key=crypto.randomUUID();game.s.Coins-=cost;game.s.Decorations.push({Key:key,Type:game.pending,X:0,Y:0});game.s.DesktopLayout['decor:'+key]={X:x/960,Y:y/540};game.s.DecorOwned++;game.pending='';game.edit=false;}else game.say('请放在空草地上。','Choose an open patch of grass.');}}
 else if(g.moved&&g.object){const o=g.object,b=bounds(o);o.x=Math.max(o.x-b[0]+6,Math.min(954-(b[0]+b[2]-o.x),x-g.dx));o.y=Math.max(o.y-b[1]+55,Math.min(478-(b[1]+b[3]-o.y),y-g.dy));if(objects().every(other=>other.id===o.id||!overlaps(solid(o),solid(other)))){game.s.DesktopLayout[o.id]={X:o.x/960,Y:o.y/540};game.say('位置已保存。','Position saved.');}else game.say('这里有其他物品，请换一块空地。','That space is occupied. Choose another spot.');}
 else if(g.moved&&g.actor){g.actor.x=Math.max(15,Math.min(945,x));g.actor.y=Math.max(140,Math.min(475,y));g.actor.tx=g.actor.x;g.actor.ty=g.actor.y;}
 else if(g.actor){if(g.actor.index<0)game.act('pet');else game.animal(g.actor.index);}
 else if(g.object?.kind==='plot')game.plot(g.object.index);else if(g.object){if(g.object.type==='station')game.act('train');else{game.panel=g.object.id==='cabin'?'settings':'workshop';game.revision++;}}save();}
 }
 const originalFetch=globalThis.fetch.bind(globalThis);
 globalThis.fetch=async(url,opts={})=>{const path=String(url);if(path==='state')return new Response(JSON.stringify(game.state()),{headers:{'Content-Type':'application/json'}});if(path==='command'){const {action,id}=JSON.parse(opts.body);if(action==='startup')post('startup',id==='on');else if(action==='call')actors.forEach(a=>{a.tx=530;a.ty=450;});else if(action==='repair')post('repair',null);else game.act(action,id);save();return new Response('ok');}if(path==='input'){input(JSON.parse(opts.body));return new Response('ok');}if(path==='ack')return new Response('ok');return originalFetch(url,opts);};
 globalThis.nativeOpenSettings=()=>{game.panel='settings';game.revision++;};
 document.addEventListener('DOMContentLoaded',()=>{const canvas=document.getElementById('farm'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;if(native){document.documentElement.style.background='transparent';document.body.style.background='transparent';}document.getElementById('status').style.display='none';let last=performance.now(),nextFrame=0;
 function syncActors(){const types=[game.s.Pet,...game.s.Animals.map(a=>a.Type)];types.forEach((type,i)=>{if(!actors[i])actors.push({type,index:i-1,x:520+i*25,y:448,tx:520,ty:448,next:0});});}
 function draw(now){requestAnimationFrame(draw);if(now<nextFrame)return;nextFrame=now+(game.s.Quiet?160:50);const dt=Math.min(.1,(now-last)/1000),t=now/1000;last=now;syncActors();const night=game.s.Lighting==='夜晚'||game.s.Lighting==='跟随时间'&&(new Date().getHours()<6||new Date().getHours()>=19),n=night?'-night':'';
 ctx.clearRect(0,0,960,540);if(!native){const bg=image('meadow'+n);if(bg.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0);}else if(lastNight!==night){post('background',night);lastNight=night;}
 const obs=objects(),draws=[];function sprite(id,x,y){const i=image(id);if(i.complete&&i.naturalWidth)ctx.drawImage(i,Math.round(x),Math.round(y));}
 function drawObject(o){if(o.kind==='plot'){const p=game.s.Plots[o.index],stage=p.Ready<=game.now?2:(game.now-p.Planted)/Math.max(1,p.Ready-p.Planted)<.25?0:1;sprite(p.Crop?'crop-'+p.Crop+'-'+stage:'plot-empty',o.x-11,o.y-36);if(p.Watered){ctx.fillStyle='#6c93a4';ctx.fillRect(o.x+7,o.y-3,2,2);}return;}let id=o.kind==='mill'?'mill'+n+'-'+Math.floor(t*1.8)%12:o.kind==='cabin'?(o.type==='bakery'?'bakery':'cabin')+n:o.kind==='building'?o.type+n:['decor','path'].includes(o.kind)?'decor-'+o.type+n:o.type;sprite(id,o.x-64,o.y-(o.kind==='pond'?90:112));}
 obs.forEach(o=>{if(gesture?.moved&&gesture.object?.id===o.id&&gesture.at){o.x=gesture.at.x-gesture.dx;o.y=gesture.at.y-gesture.dy;}draws.push({y:o.kind==='path'?0:o.y,draw:()=>drawObject(o)});});
 actors.forEach((a,i)=>{if(t>a.next||Math.hypot(a.x-a.tx,a.y-a.ty)<5){a.next=t+5+Math.random()*8;a.tx=30+Math.random()*900;a.ty=150+Math.random()*330;if(game.s.Weather==='雨天'){const home=obs.find(o=>o.id==='cabin');a.tx=home.x+48;a.ty=home.y+20;}}const d=Math.hypot(a.tx-a.x,a.ty-a.y),dx=(a.tx-a.x)/Math.max(1,d)*dt*14,dy=(a.ty-a.y)/Math.max(1,d)*dt*14;if(!obs.some(o=>solid(o)&&inside(a.x+dx,a.y+dy,solid(o)))){a.x+=dx;a.y+=dy;}else{a.next=0;}draws.push({y:a.y,draw:()=>sprite('actor-'+a.type+'-'+Math.floor(t*4)%4,a.x-64,a.y-112)});});draws.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());
 if(game.s.Weather==='雨天'||game.s.Weather==='雪天'){ctx.fillStyle=game.s.Weather==='雨天'?'#bad4c6':'#f6f0da';for(let i=0;i<60;i++)ctx.fillRect((i*71+t*12)%960,(i*47+t*(game.s.Weather==='雨天'?70:16))%540,game.s.Weather==='雨天'?1:2,game.s.Weather==='雨天'?5:2);}
 if(native){const regions=obs.map(o=>bounds(o).map((v,i)=>v/(i%2?540:960)));for(const a of actors)regions.push([(a.x-20)/960,(a.y-26)/540,40/960,30/540]);for(const id of ['resources','dock','drawer','mode']){const e=document.getElementById(id);if(getComputedStyle(e).display!=='none'){const r=e.getBoundingClientRect();regions.push([r.x/innerWidth,r.y/innerHeight,r.width/innerWidth,r.height/innerHeight]);}}if(game.pending)regions.push([0,0,1,1]);post('regions',regions);}
 }requestAnimationFrame(draw);setInterval(save,15000);window.addEventListener('pagehide',save);});
 globalThis.MossScene={objects,bounds,input,save};
})();
