/* Local, offline game simulation. No network, Windows process or wallpaper software required. */
class MossFarm {
 constructor(saved,clock=()=>Date.now()/1000){this.clock=clock;this.note='';this.noteUntil=0;this.pending='';this.edit=false;this.panel='';this.revision=0;this.startup=false;
 this.s=saved?structuredClone(saved):structuredClone(FARM_DATA.initial);if(!saved){this.s.LastSeen=this.now;this.s.Plots.forEach((p,i)=>{if(p.Crop){p.Planted=this.now-120;p.Ready=this.now+(i===0?-1:12+i*7);}});this.s.HudZoom=75;}this.validate();this.tick();}
 get now(){return this.clock()} get level(){let n=1;while(n<20&&this.s.Xp>=this.threshold(n+1))n++;return n} threshold(n){return(n-1)*20+(n-1)**2*5}
 validate(){const s=this.s;if(s.Version!==1||!Number.isFinite(s.Coins)||s.Coins<0||!Number.isFinite(s.Xp)||s.Xp<0||![0,1,2].includes(s.Land)||!Array.isArray(s.Plots)||s.Plots.length!==12*(s.Land+1)||!Array.isArray(s.OrdersList)||s.OrdersList.length!==3||!s.Inventory||!s.Buildings||!s.Queues||!Array.isArray(s.Animals)||!Array.isArray(s.Decorations)||!Array.isArray(s.Achievements))throw Error('Invalid farm save');for(const p of s.Plots)if(p.Crop&&!this.crop(p.Crop)||!Number.isFinite(p.Ready))throw Error('Invalid crop');for(const [b,q] of Object.entries(s.Queues)){if(!Array.isArray(q)||q.length>4||q.length&&!s.Buildings[b])throw Error('Invalid queue');for(const j of q)if(!this.recipe(j.Recipe)||this.recipe(j.Recipe).Building!==b||!Number.isFinite(j.Ready))throw Error('Invalid job');}for(const [id,n] of Object.entries(s.Inventory))if(!Number.isInteger(n)||n<0)throw Error('Invalid inventory');s.DesktopLayout??={};for(const p of Object.values(s.DesktopLayout))if(!Number.isFinite(p.X)||!Number.isFinite(p.Y))throw Error('Invalid layout');s.Language=s.Language==='en'?'en':'zh-CN';if(!this.crop(s.SelectedSeed))s.SelectedSeed='wheat';s.HudZoom=[50,75,85,100,125,150].includes(s.HudZoom)?s.HudZoom:75;}
 tr(zh,en){return this.s.Language==='en'?en:zh} name(id){const zh=this.crop(id)?.Name||this.recipe(id)?.Name||FARM_DATA.buildings.find(b=>b.id===id)?.name||({egg:'鸡蛋',milk:'牛奶',wool:'羊毛',honey:'蜂蜜',home:'木屋',path:'道路',flowers:'花坛',fence:'木围栏',lamp:'路灯',bench:'长椅',tree:'苹果树',fountain:'小喷泉'})[id]||id;return this.tr(zh,(globalThis.FARM_EN?.[zh])||id.replace(/\b\w/g,c=>c.toUpperCase()));}
 crop(id){return FARM_DATA.crops.find(c=>c.Id===id)} recipe(id){return FARM_DATA.recipes.find(r=>r.Id===id)} count(id){return this.s.Inventory[id]||0} add(id,n){this.s.Inventory[id]=Math.max(0,this.count(id)+n)} gain(c,x){this.s.Coins+=c;this.s.LifetimeCoins+=c;this.s.Xp+=x} price(id){return this.crop(id)?.Price||this.recipe(id)?.Price||({egg:18,milk:30,wool:45,honey:55})[id]||0}
 say(zh,en){this.note=this.tr(zh,en);this.noteUntil=this.now+5;return this.note}
 tick(){for(const q of Object.values(this.s.Queues))while(q.length&&q[0].Ready<=this.now){this.add(q.shift().Recipe,1);this.s.Made++;this.gain(0,5);}this.achievements();if(this.s.Coins<2&&Object.values(this.s.Inventory).every(n=>n===0)&&this.s.Plots.every(p=>!p.Crop)&&Object.values(this.s.Queues).every(q=>!q.length)&&this.s.Animals.every(a=>!a.Fed))this.gain(10,0);this.s.LastSeen=this.now;}
 achievements(){for(const [id,yes,coins] of [['first',this.s.Harvests>=1,15],['maker',this.s.Made>=1,25],['orders',this.s.Orders>=5,70],['harvest',this.s.Harvests>=50,100],['friend',this.s.PetLove>=20,40],['land',this.s.Land>=1,50],['rich',this.s.LifetimeCoins>=3000,150]])if(yes&&!this.s.Achievements.includes(id)){this.s.Achievements.push(id);this.gain(coins,5);}}
 plant(i){const p=this.s.Plots[i],c=this.crop(this.s.SelectedSeed);if(!p||p.Crop||!c||c.Level>this.level||this.s.Coins<c.Cost)return false;this.s.Coins-=c.Cost;Object.assign(p,{Crop:c.Id,Planted:this.now,Ready:this.now+c.Seconds,Watered:false});this.s.Planted++;return true}
 harvest(i){const p=this.s.Plots[i];if(!p?.Crop||p.Ready>this.now)return false;const c=this.crop(p.Crop);this.add(c.Id,3);this.s.Harvests++;this.gain(0,c.Xp);p.Crop='';p.Watered=false;this.achievements();return true}
 plot(i){const p=this.s.Plots[i];if(!p)return;if(!p.Crop){if(this.plant(i))this.say('种下'+this.name(this.s.SelectedSeed),'Planted '+this.name(this.s.SelectedSeed));else this.say('金币不足或尚未解锁。','Not enough coins, or this crop is locked.');}else if(this.harvest(i))this.say('收获已入仓。','Harvest stored.');else if(!p.Watered){p.Watered=true;p.Ready=this.now+(p.Ready-this.now)*.8;this.say('浇水完成，剩余时间缩短 20%。','Watered: remaining growth time reduced by 20%.');}else this.say('作物还在生长。','This crop is still growing.');}
 canCraft(r){return this.s.Buildings[r.Building]&&this.level>=r.Level&&(this.s.Queues[r.Building]||[]).length<this.s.Buildings[r.Building]+1&&Object.entries(r.Inputs).every(([id,n])=>this.count(id)>=n)}
 canOrder(o){return Object.entries(o.Items).every(([id,n])=>this.count(id)>=n)}
 orders(completed){return [0,1,2].map(i=>{const k=(completed+i)%4,Items={};if(this.level<2)Items.wheat=4+i*2;else if(this.level<4){Items.wheat=3+i;Items[i===1?'flour':'corn']=i===1?1:2;}else{Items[i===0?'bread':i===1?'carrot':'strawberry']=i===0?1:3;Items.wheat=3;}return {Person:['莉莉 · 花店','诺亚 · 木匠','艾米 · 旅店','山谷集市'][k],Text:'',Items,Coins:Math.floor(Object.entries(Items).reduce((v,[id,n])=>v+this.price(id)*n,0)*1.4),Xp:12+i*3};});}
 get guideDone(){return [this.s.Harvests>0,this.s.Planted>0,this.s.Made>0||Object.values(this.s.Queues).some(q=>q.length),this.s.Sold>0,this.s.Orders>0,this.s.Petting>0,this.s.Land>0,false][this.s.Guide]||false}
 get expandCost(){return [150,400,0][this.s.Land]} decorCost(id){return {path:5,flowers:25,fence:20,lamp:55,bench:45,tree:70,fountain:90}[id]}
 animal(i){const a=this.s.Animals[i];if(!a)return;if(a.Fed){if(a.Ready>this.now)return this.say('小动物正在休息。','Your animal is resting.');this.add(({chicken:'egg',cow:'milk',sheep:'wool',bee:'honey'})[a.Type],2);a.Fed=false;this.gain(0,8);return this.say('动物产品 +2','Animal products +2');}const food=this.count('feed')>0?'feed':'wheat',n=food==='feed'?1:3;if(this.count(food)<n)return this.say('需要 1 份饲料或 3 份小麦。','Needs 1 feed or 3 wheat.');this.add(food,-n);a.Fed=true;a.Ready=this.now+(a.Type==='chicken'?180:a.Type==='cow'?600:900);this.say('喂食完成。','Animal fed.');}
 act(action,id=''){this.tick();switch(action){case 'seed':if(this.crop(id)?.Level<=this.level)this.s.SelectedSeed=id;break;case 'harvest':this.s.Plots.forEach((_,i)=>this.harvest(i));break;case 'plant':this.s.Plots.forEach((_,i)=>this.plant(i));break;
 case 'sell':if(this.count(id)>0){this.add(id,-1);this.gain(this.price(id),1);this.s.Sold++;}break;
 case 'craft':{const r=this.recipe(id);if(r&&this.canCraft(r)){Object.entries(r.Inputs).forEach(([k,n])=>this.add(k,-n));const q=this.s.Queues[r.Building]??=[];q.push({Recipe:id,Ready:Math.max(this.now,q.at(-1)?.Ready||0)+r.Seconds*(this.s.Buildings[r.Building]>=3?.9:1)});}break;}
 case 'order':{const i=Number(id),o=this.s.OrdersList[i];if(o&&this.canOrder(o)){Object.entries(o.Items).forEach(([k,n])=>this.add(k,-n));this.gain(o.Coins,o.Xp);this.s.Orders++;this.s.OrdersList[i]=this.orders(this.s.Orders+i)[i];}break;}
 case 'build':{const b=FARM_DATA.buildings.find(b=>b.id===id),lv=this.s.Buildings[id];if(!b)break;if(lv){if(!['coop','barn','station'].includes(id)&&lv<3&&this.s.Coins>=lv*160){this.s.Coins-=lv*160;this.s.Buildings[id]++;}}else if(this.level>=b.level&&this.s.Coins>=b.cost){this.s.Coins-=b.cost;this.s.Buildings[id]=1;this.gain(0,10);if(['coop','barn'].includes(id))this.s.Animals.push({Type:id==='coop'?'chicken':'cow',Fed:false,Ready:0});}break;}
 case 'expand':if(this.s.Land<2&&this.level>=(this.s.Land===0?2:5)&&this.s.Coins>=this.expandCost){this.s.Coins-=this.expandCost;this.s.Land++;this.s.Plots.push(...Array.from({length:12},()=>({Crop:'',Ready:0,Planted:0,Watered:false})));this.gain(0,20);}break;
 case 'daily':{const d=new Date(this.now*1000),key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');if(this.s.DailyClaim!==key){this.s.DailyClaim=key;this.gain(35,5);this.add('wheat',3);}break;}
 case 'guide':if(this.guideDone){this.s.Guide++;this.gain(20,5);}break;
 case 'pet':this.s.Petting++;if(this.now-this.s.LastPet>=60){this.s.LastPet=this.now;this.s.PetLove=Math.min(999,this.s.PetLove+2);}this.say('小伙伴好感度：'+this.s.PetLove,'Companion affection: '+this.s.PetLove);break;
 case 'train':if(this.s.Buildings.station&&this.count('bread')>=5&&this.count('milk')>=6&&this.count('jam')>=2){this.add('bread',-5);this.add('milk',-6);this.add('jam',-2);this.gain(1500,90);this.s.Orders++;this.say('列车满载出发！金币 +1500','Train dispatched! +1500 coins');}else this.say('列车需要：面包 ×5、牛奶 ×6、果酱 ×2。','Train needs 5 bread, 6 milk and 2 jam.');break;
 case 'zoom':if([50,75,85,100,125,150].includes(Number(id)))this.s.HudZoom=Number(id);break;case 'language':this.s.Language=id==='en'?'en':'zh-CN';break;case 'quiet':this.s.Quiet=id==='on';break;case 'weather':if(['自动','晴天','雨天','雪天'].includes(id))this.s.Weather=id;break;case 'light':if(['跟随时间','白天','夜晚'].includes(id))this.s.Lighting=id;break;case 'edit':this.edit=!this.edit;break;case 'cancel':this.pending='';this.edit=false;break;case 'decor':if(this.decorCost(id)!=null&&this.s.Coins>=this.decorCost(id)){this.pending=id;this.edit=true;}break;}this.achievements();}
 state(){this.tick();const s=this.s,qty=inputs=>Object.entries(inputs).map(([id,n])=>this.name(id)+' '+this.count(id)+'/'+n).join(' · ');return {quiet:s.Quiet,startup:this.startup,startupAllowed:!!globalThis.webkit?.messageHandlers?.farm,weather:s.Weather,zoom:s.HudZoom,coins:s.Coins,level:this.level,xp:s.Xp-this.threshold(this.level),xpMax:this.level<20?this.threshold(this.level+1)-this.threshold(this.level):0,language:s.Language,seed:s.SelectedSeed,edit:this.edit,pending:this.pending?this.name(this.pending):'',note:this.now<this.noteUntil?this.note:'',panel:this.panel,revision:this.revision,ready:s.Plots.filter(p=>p.Crop&&p.Ready<=this.now).length,empty:s.Plots.filter(p=>!p.Crop).length,land:s.Plots.length,expandCost:this.expandCost,canExpand:s.Land<2&&this.level>=(s.Land===0?2:5)&&s.Coins>=this.expandCost,crops:FARM_DATA.crops.map(c=>({id:c.Id,name:this.name(c.Id),cost:c.Cost,seconds:c.Seconds,level:c.Level,owned:this.count(c.Id)})),inventory:Object.entries(s.Inventory).filter(([_,n])=>n>0).map(([id,count])=>({id,count,name:this.name(id),price:this.price(id)})),recipes:FARM_DATA.recipes.map(r=>({id:r.Id,name:this.name(r.Id),seconds:r.Seconds,building:this.name(r.Building),level:r.Level,can:!!this.canCraft(r),ingredients:qty(r.Inputs)})),jobs:Object.values(s.Queues).flat().map(j=>({name:this.name(j.Recipe),seconds:Math.max(0,j.Ready-this.now)})),orders:s.OrdersList.map((o,id)=>({id,name:this.tr(o.Person,FARM_EN[o.Person]||'Valley market'),coins:o.Coins,xp:o.Xp,can:this.canOrder(o),items:qty(o.Items)})),buildings:FARM_DATA.buildings.map(b=>({id:b.id,name:this.name(b.id),owned:!!s.Buildings[b.id],level:b.level,cost:s.Buildings[b.id]?s.Buildings[b.id]*160:b.cost,can:s.Buildings[b.id]?s.Buildings[b.id]<3&&!['coop','barn','station'].includes(b.id)&&s.Coins>=s.Buildings[b.id]*160:this.level>=b.level&&s.Coins>=b.cost})),decor:['path','flowers','fence','lamp','bench','tree','fountain'].map(id=>({id,name:this.name(id),cost:this.decorCost(id)})),guide:this.tr(['收获第一块金色小麦','在空地种下一粒种子','制作一袋面粉','出售一份商品','完成一张订单','摸摸小猫','扩建土地','享受农场生活'][s.Guide],['Harvest wheat','Plant a seed','Make flour','Sell a product','Deliver an order','Pet your cat','Expand your land','Enjoy your farm'][s.Guide]),guideDone:this.guideDone,lighting:s.Lighting};}
}
globalThis.MossFarm=MossFarm;
