using System;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Principal;
using Microsoft.Win32;

static class Setup {
 public static readonly string InstallRoot=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Applications","MosslightFarm","1.1");
 static bool Chinese=System.Globalization.CultureInfo.CurrentUICulture.Name.StartsWith("zh");
 public static string T(string zh,string en){return Chinese?zh:en;}
 [STAThread]static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{
 if(args.Length==2&&args[0]=="--extract-only"){Extract(args[1]);return;}
 if(args.Length==1&&args[0]=="--install-unattended"){Install(ExistingStartup(),s=>{});return;}
 Application.Run(new InstallForm());}catch(Exception e){File.WriteAllText(Path.Combine(Path.GetTempPath(),"Mosslight-Setup-error.txt"),e.ToString());Environment.ExitCode=1;if(args.Length==0)MessageBox.Show(e.Message,"Mosslight Setup",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 public static void Extract(string destination){string root=Path.GetFullPath(destination).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;Directory.CreateDirectory(root);using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("payload.zip"))using(var zip=new ZipArchive(stream,ZipArchiveMode.Read)){foreach(var e in zip.Entries){string path=Path.GetFullPath(Path.Combine(root,e.FullName));if(!path.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new IOException("Invalid package path");if(string.IsNullOrEmpty(e.Name)){Directory.CreateDirectory(path);continue;}Directory.CreateDirectory(Path.GetDirectoryName(path));using(var input=e.Open())using(var output=File.Create(path))input.CopyTo(output);}}foreach(string file in new[]{"MosslightFarm.exe","MosslightFarmUninstall.exe","Microsoft.Web.WebView2.Core.dll","Microsoft.Web.WebView2.WinForms.dll","WebView2Loader.dll","assets/desktop.html"})if(!File.Exists(Path.Combine(root,file)))throw new IOException("Package is incomplete: "+file);}
 public static bool ExistingStartup(){try{dynamic service=Activator.CreateInstance(Type.GetTypeFromProgID("Schedule.Service"));service.Connect();return service.GetFolder("\\").GetTask("MosslightFarm-"+WindowsIdentity.GetCurrent().User.Value).Enabled;}catch{return false;}}
 static void StopExisting(){EventWaitHandle signal;if(EventWaitHandle.TryOpenExisting("Local\\MosslightFarm-Player-Quit",out signal)){using(signal)signal.Set();}Mutex mutex;if(Mutex.TryOpenExisting("MosslightFarm-Player",out mutex)){using(mutex){bool stopped=false;try{stopped=mutex.WaitOne(15000);}catch(AbandonedMutexException){stopped=true;}if(!stopped)throw new Exception(T("请先在旧版农场菜单中选择保存并退出，再重新安装。","Please choose Save and exit in the old farm, then retry installation."));mutex.ReleaseMutex();}}}
 static int Run(string exe,string args,int timeout){using(var process=Process.Start(new ProcessStartInfo(exe,args){WorkingDirectory=Path.GetDirectoryName(exe),UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden})){if(!process.WaitForExit(timeout))throw new Exception(T("安装组件仍在运行，请稍后重试。","Component installation is still running. Please retry later."));return process.ExitCode;}}
 public static void Shortcut(string folder,string name,string exe,string args){Directory.CreateDirectory(folder);dynamic shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic link=shell.CreateShortcut(Path.Combine(folder,name+".lnk"));link.TargetPath=exe;link.Arguments=args;link.WorkingDirectory=Path.GetDirectoryName(exe);link.IconLocation=exe+",0";link.Description=name;link.Save();}
 static void RegisterUninstall(){string uninstaller=Path.Combine(InstallRoot,"MosslightFarmUninstall.exe");if(!File.Exists(uninstaller))throw new FileNotFoundException("Uninstaller is missing.",uninstaller);string game=Path.Combine(InstallRoot,"MosslightFarm.exe");long size=0;foreach(string file in Directory.GetFiles(InstallRoot,"*",SearchOption.AllDirectories))try{size+=new FileInfo(file).Length;}catch{}using(RegistryKey key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\MosslightFarm")){key.SetValue("DisplayName","Mosslight Farm | 苔光农场",RegistryValueKind.String);key.SetValue("DisplayVersion","1.1",RegistryValueKind.String);key.SetValue("Publisher","Mosslight Farm",RegistryValueKind.String);key.SetValue("InstallLocation",InstallRoot,RegistryValueKind.String);key.SetValue("DisplayIcon",game+",0",RegistryValueKind.String);key.SetValue("UninstallString","\""+uninstaller+"\"",RegistryValueKind.String);key.SetValue("QuietUninstallString","\""+uninstaller+"\" --quiet",RegistryValueKind.String);key.SetValue("InstallDate",DateTime.Now.ToString("yyyyMMdd"),RegistryValueKind.String);key.SetValue("EstimatedSize",(int)Math.Min(int.MaxValue,Math.Max(1,size/1024)),RegistryValueKind.DWord);key.SetValue("NoModify",1,RegistryValueKind.DWord);key.SetValue("NoRepair",1,RegistryValueKind.DWord);}}
 public static void Install(bool startup,Action<string> status){if(!Environment.Is64BitOperatingSystem)throw new Exception("Mosslight requires 64-bit Windows 10 or 11.");status(T("正在安全关闭旧版农场…","Saving and closing the existing farm…"));StopExisting();status(T("正在安装完整游戏…","Installing the complete game…"));Extract(InstallRoot);string exe=Path.Combine(InstallRoot,"MosslightFarm.exe");status(T("正在检查显示组件…","Checking the display runtime…"));if(Run(exe,"--check-runtime",30000)!=0){status(T("正在从 Microsoft 安装 WebView2，需要联网…","Installing WebView2 from Microsoft; internet required…"));Run(Path.Combine(InstallRoot,"runtime","MicrosoftEdgeWebview2Setup.exe"),"/silent /install",300000);if(Run(exe,"--check-runtime",30000)!=0)throw new Exception(T("显示组件未安装成功。请联网后重新运行此安装包。","The display runtime could not be installed. Connect to the internet and rerun this setup."));}
 status(T("正在创建桌面入口…","Creating desktop shortcuts…"));Shortcut(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"Mosslight Farm",exe,"--desktop");string menu=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Programs),"Mosslight Farm");Shortcut(menu,"Mosslight Farm",exe,"--desktop");Shortcut(menu,"Mosslight Management",exe,"--manage");if(Run(exe,"--set-autostart "+(startup?"on":"off"),30000)!=0)throw new Exception("Could not update login startup.");status(T("正在登记 Windows 卸载入口…","Registering the Windows uninstall entry…"));RegisterUninstall();status(T("正在启动互动壁纸…","Starting the interactive wallpaper…"));Process.Start(new ProcessStartInfo(exe,"--desktop"){WorkingDirectory=InstallRoot,UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden});}
 sealed class InstallForm:Form {
 readonly Label status=new Label();readonly Button install=new Button();readonly CheckBox startup=new CheckBox();readonly ProgressBar progress=new ProgressBar();bool busy,done;
 public InstallForm(){Text="Mosslight Farm · Setup 1.1";ClientSize=new Size(530,325);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;BackColor=Color.FromArgb(246,240,220);Font=new Font("Segoe UI",10);Controls.Add(new Label{Text="Mosslight Farm",Font=new Font("Segoe UI",23,FontStyle.Bold),ForeColor=Color.FromArgb(70,98,72),Location=new Point(28,23),AutoSize=true});Controls.Add(new Label{Text=T("安装互动桌面农场，无需 Wallpaper Engine。\n首次缺少显示组件时会从 Microsoft 联网安装。","Install your interactive desktop farm. No Wallpaper Engine needed.\nIf missing, WebView2 is installed online from Microsoft."),Location=new Point(30,85),Size=new Size(474,56)});startup.Text=T("登录 Windows 后自动启动","Start automatically when I sign in to Windows");startup.Checked=ExistingStartup();startup.SetBounds(30,147,470,28);Controls.Add(startup);status.Text=InstallRoot;status.SetBounds(30,182,470,43);Controls.Add(status);progress.SetBounds(30,230,470,8);Controls.Add(progress);install.Text=T("安装并进入桌面","Install and start wallpaper");install.SetBounds(258,259,242,40);install.BackColor=Color.FromArgb(213,227,190);Controls.Add(install);install.Click+=async(s,e)=>{if(done){Close();return;}busy=true;install.Enabled=false;startup.Enabled=false;progress.Style=ProgressBarStyle.Marquee;bool boot=startup.Checked;try{await Task.Run(()=>Install(boot,message=>BeginInvoke((Action)(()=>status.Text=message))));done=true;status.Text=T("安装完成。以后双击桌面的 Mosslight Farm 即可。","Installed. Use Mosslight Farm on your desktop to return to the farm.");install.Text=T("完成","Done");}catch(Exception ex){status.Text=ex.Message;install.Text=T("重试","Retry");startup.Enabled=true;}finally{busy=false;progress.Style=ProgressBarStyle.Continuous;progress.Value=done?100:0;install.Enabled=true;}};FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};}
 }
}

